:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]
:LiquidityPenaltyHook: pass:normal[xref:general.adoc#LiquidityPenaltyHook[`LiquidityPenaltyHook`]]
:AntiSandwichHook: pass:normal[xref:general.adoc#AntiSandwichHook[`AntiSandwichHook`]]
:LimitOrderHook: pass:normal[xref:general.adoc#LimitOrderHook[`LimitOrderHook`]]
:ReHypothecationHook: pass:normal[xref:general.adoc#ReHypothecationHook[`ReHypothecationHook`]]
:xref-LiquidityPenaltyHook-constructor-uint48-: xref:general.adoc#LiquidityPenaltyHook-constructor-uint48-
:xref-LiquidityPenaltyHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:general.adoc#LiquidityPenaltyHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-LiquidityPenaltyHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:general.adoc#LiquidityPenaltyHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-LiquidityPenaltyHook-_getBlockNumber--: xref:general.adoc#LiquidityPenaltyHook-_getBlockNumber--
:xref-LiquidityPenaltyHook-_updateLastAddedLiquidityBlock-PoolId-bytes32-: xref:general.adoc#LiquidityPenaltyHook-_updateLastAddedLiquidityBlock-PoolId-bytes32-
:xref-LiquidityPenaltyHook-_takeFeesToHook-struct-PoolKey-bytes32-BalanceDelta-: xref:general.adoc#LiquidityPenaltyHook-_takeFeesToHook-struct-PoolKey-bytes32-BalanceDelta-
:xref-LiquidityPenaltyHook-_settleFeesFromHook-struct-PoolKey-bytes32-: xref:general.adoc#LiquidityPenaltyHook-_settleFeesFromHook-struct-PoolKey-bytes32-
:xref-LiquidityPenaltyHook-_calculateLiquidityPenalty-BalanceDelta-uint48-: xref:general.adoc#LiquidityPenaltyHook-_calculateLiquidityPenalty-BalanceDelta-uint48-
:xref-LiquidityPenaltyHook-getLastAddedLiquidityBlock-PoolId-bytes32-: xref:general.adoc#LiquidityPenaltyHook-getLastAddedLiquidityBlock-PoolId-bytes32-
:xref-LiquidityPenaltyHook-getWithheldFees-PoolId-bytes32-: xref:general.adoc#LiquidityPenaltyHook-getWithheldFees-PoolId-bytes32-
:xref-LiquidityPenaltyHook-getHookPermissions--: xref:general.adoc#LiquidityPenaltyHook-getHookPermissions--
:xref-LiquidityPenaltyHook-MIN_BLOCK_NUMBER_OFFSET-uint48: xref:general.adoc#LiquidityPenaltyHook-MIN_BLOCK_NUMBER_OFFSET-uint48
:xref-LiquidityPenaltyHook-blockNumberOffset-uint48: xref:general.adoc#LiquidityPenaltyHook-blockNumberOffset-uint48
:xref-BaseHook-_validateHookAddress-contract-BaseHook-: xref:base.adoc#BaseHook-_validateHookAddress-contract-BaseHook-
:xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-: xref:base.adoc#BaseHook-beforeInitialize-address-struct-PoolKey-uint160-
:xref-BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-: xref:base.adoc#BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-
:xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-: xref:base.adoc#BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-: xref:base.adoc#BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:base.adoc#BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-BaseHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:base.adoc#BaseHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-BaseHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:base.adoc#BaseHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-poolManager-contract-IPoolManager: xref:base.adoc#BaseHook-poolManager-contract-IPoolManager
:xref-LiquidityPenaltyHook-BlockNumberOffsetTooLow--: xref:general.adoc#LiquidityPenaltyHook-BlockNumberOffsetTooLow--
:xref-LiquidityPenaltyHook-NoLiquidityToReceiveDonation--: xref:general.adoc#LiquidityPenaltyHook-NoLiquidityToReceiveDonation--
:xref-BaseHook-HookNotImplemented--: xref:base.adoc#BaseHook-HookNotImplemented--
:xref-BaseHook-NotPoolManager--: xref:base.adoc#BaseHook-NotPoolManager--
:xref-BaseHook-InvalidPool--: xref:base.adoc#BaseHook-InvalidPool--
:xref-AntiSandwichHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:general.adoc#AntiSandwichHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-AntiSandwichHook-_getBlockNumber--: xref:general.adoc#AntiSandwichHook-_getBlockNumber--
:xref-AntiSandwichHook-getLastCheckpoint-PoolId-: xref:general.adoc#AntiSandwichHook-getLastCheckpoint-PoolId-
:xref-AntiSandwichHook-_getTargetUnspecified-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:general.adoc#AntiSandwichHook-_getTargetUnspecified-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-AntiSandwichHook-getHookPermissions--: xref:general.adoc#AntiSandwichHook-getHookPermissions--
:xref-BaseDynamicAfterFee-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:fee.adoc#BaseDynamicAfterFee-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-BaseDynamicAfterFee-_afterSwapHandler-struct-PoolKey-struct-SwapParams-BalanceDelta-uint256-uint256-: xref:fee.adoc#BaseDynamicAfterFee-_afterSwapHandler-struct-PoolKey-struct-SwapParams-BalanceDelta-uint256-uint256-
:xref-BaseHook-_validateHookAddress-contract-BaseHook-: xref:base.adoc#BaseHook-_validateHookAddress-contract-BaseHook-
:xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-: xref:base.adoc#BaseHook-beforeInitialize-address-struct-PoolKey-uint160-
:xref-BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-: xref:base.adoc#BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-
:xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-: xref:base.adoc#BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-: xref:base.adoc#BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:base.adoc#BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-poolManager-contract-IPoolManager: xref:base.adoc#BaseHook-poolManager-contract-IPoolManager
:xref-IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-: xref:interfaces.adoc#IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-
:xref-IHookEvents-HookFee-bytes32-address-uint128-uint128-: xref:interfaces.adoc#IHookEvents-HookFee-bytes32-address-uint128-uint128-
:xref-IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-: xref:interfaces.adoc#IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-
:xref-IHookEvents-HookBonus-bytes32-uint128-uint128-: xref:interfaces.adoc#IHookEvents-HookBonus-bytes32-uint128-uint128-
:xref-AntiSandwichHook-CheckpointNotSet--: xref:general.adoc#AntiSandwichHook-CheckpointNotSet--
:xref-AntiSandwichHook-TargetOutOfRange--: xref:general.adoc#AntiSandwichHook-TargetOutOfRange--
:xref-BaseHook-HookNotImplemented--: xref:base.adoc#BaseHook-HookNotImplemented--
:xref-BaseHook-NotPoolManager--: xref:base.adoc#BaseHook-NotPoolManager--
:xref-BaseHook-InvalidPool--: xref:base.adoc#BaseHook-InvalidPool--
:BaseDynamicAfterFee-_afterSwap: pass:normal[xref:fee.adoc#BaseDynamicAfterFee-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-[`BaseDynamicAfterFee._afterSwap`]]
:xref-LimitOrderHook-_afterInitialize-address-struct-PoolKey-uint160-int24-: xref:general.adoc#LimitOrderHook-_afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-LimitOrderHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:general.adoc#LimitOrderHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-LimitOrderHook-placeOrder-struct-PoolKey-int24-bool-uint128-: xref:general.adoc#LimitOrderHook-placeOrder-struct-PoolKey-int24-bool-uint128-
:xref-LimitOrderHook-cancelOrder-struct-PoolKey-int24-bool-address-: xref:general.adoc#LimitOrderHook-cancelOrder-struct-PoolKey-int24-bool-address-
:xref-LimitOrderHook-withdraw-OrderIdLibrary-OrderId-address-: xref:general.adoc#LimitOrderHook-withdraw-OrderIdLibrary-OrderId-address-
:xref-LimitOrderHook-unlockCallback-bytes-: xref:general.adoc#LimitOrderHook-unlockCallback-bytes-
:xref-LimitOrderHook-_handlePlaceCallback-struct-LimitOrderHook-PlaceCallbackData-: xref:general.adoc#LimitOrderHook-_handlePlaceCallback-struct-LimitOrderHook-PlaceCallbackData-
:xref-LimitOrderHook-_handleCancelCallback-struct-LimitOrderHook-CancelCallbackData-: xref:general.adoc#LimitOrderHook-_handleCancelCallback-struct-LimitOrderHook-CancelCallbackData-
:xref-LimitOrderHook-_handleWithdrawCallback-struct-LimitOrderHook-WithdrawCallbackData-: xref:general.adoc#LimitOrderHook-_handleWithdrawCallback-struct-LimitOrderHook-WithdrawCallbackData-
:xref-LimitOrderHook-_fillCrossedOrders-struct-PoolKey-bool-: xref:general.adoc#LimitOrderHook-_fillCrossedOrders-struct-PoolKey-bool-
:xref-LimitOrderHook-_fillOrder-struct-PoolKey-int24-bool-: xref:general.adoc#LimitOrderHook-_fillOrder-struct-PoolKey-int24-bool-
:xref-LimitOrderHook-_getCrossedTicks-PoolId-int24-: xref:general.adoc#LimitOrderHook-_getCrossedTicks-PoolId-int24-
:xref-LimitOrderHook-_getTickLower-int24-int24-: xref:general.adoc#LimitOrderHook-_getTickLower-int24-int24-
:xref-LimitOrderHook-_getCurrentTick-PoolId-: xref:general.adoc#LimitOrderHook-_getCurrentTick-PoolId-
:xref-LimitOrderHook-_getPositionSalt-bool-: xref:general.adoc#LimitOrderHook-_getPositionSalt-bool-
:xref-LimitOrderHook-getTickLowerLast-PoolId-: xref:general.adoc#LimitOrderHook-getTickLowerLast-PoolId-
:xref-LimitOrderHook-getOrderId-struct-PoolKey-int24-bool-: xref:general.adoc#LimitOrderHook-getOrderId-struct-PoolKey-int24-bool-
:xref-LimitOrderHook-getOrderInfo-OrderIdLibrary-OrderId-: xref:general.adoc#LimitOrderHook-getOrderInfo-OrderIdLibrary-OrderId-
:xref-LimitOrderHook-getUserInfo-OrderIdLibrary-OrderId-address-: xref:general.adoc#LimitOrderHook-getUserInfo-OrderIdLibrary-OrderId-address-
:xref-LimitOrderHook-getHookPermissions--: xref:general.adoc#LimitOrderHook-getHookPermissions--
:xref-BaseHook-_validateHookAddress-contract-BaseHook-: xref:base.adoc#BaseHook-_validateHookAddress-contract-BaseHook-
:xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-: xref:base.adoc#BaseHook-beforeInitialize-address-struct-PoolKey-uint160-
:xref-BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-: xref:base.adoc#BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-
:xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-: xref:base.adoc#BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:base.adoc#BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-BaseHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:base.adoc#BaseHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-poolManager-contract-IPoolManager: xref:base.adoc#BaseHook-poolManager-contract-IPoolManager
:xref-LimitOrderHook-Place-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-: xref:general.adoc#LimitOrderHook-Place-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-
:xref-LimitOrderHook-Fill-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-: xref:general.adoc#LimitOrderHook-Fill-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-
:xref-LimitOrderHook-Cancel-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-: xref:general.adoc#LimitOrderHook-Cancel-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-
:xref-LimitOrderHook-Withdraw-address-OrderIdLibrary-OrderId-uint128-: xref:general.adoc#LimitOrderHook-Withdraw-address-OrderIdLibrary-OrderId-uint128-
:xref-LimitOrderHook-ZeroLiquidity--: xref:general.adoc#LimitOrderHook-ZeroLiquidity--
:xref-LimitOrderHook-InRange--: xref:general.adoc#LimitOrderHook-InRange--
:xref-LimitOrderHook-CrossedRange--: xref:general.adoc#LimitOrderHook-CrossedRange--
:xref-LimitOrderHook-Filled--: xref:general.adoc#LimitOrderHook-Filled--
:xref-LimitOrderHook-NotFilled--: xref:general.adoc#LimitOrderHook-NotFilled--
:xref-LimitOrderHook-NativeCurrencyUnsupported--: xref:general.adoc#LimitOrderHook-NativeCurrencyUnsupported--
:xref-BaseHook-HookNotImplemented--: xref:base.adoc#BaseHook-HookNotImplemented--
:xref-BaseHook-NotPoolManager--: xref:base.adoc#BaseHook-NotPoolManager--
:xref-BaseHook-InvalidPool--: xref:base.adoc#BaseHook-InvalidPool--
:xref-LimitOrderHook-ZERO_BYTES-bytes: xref:general.adoc#LimitOrderHook-ZERO_BYTES-bytes
:xref-LimitOrderHook-ORDER_ID_DEFAULT-OrderIdLibrary-OrderId: xref:general.adoc#LimitOrderHook-ORDER_ID_DEFAULT-OrderIdLibrary-OrderId
:xref-ReHypothecationHook-getPoolKey--: xref:general.adoc#ReHypothecationHook-getPoolKey--
:xref-ReHypothecationHook-_beforeInitialize-address-struct-PoolKey-uint160-: xref:general.adoc#ReHypothecationHook-_beforeInitialize-address-struct-PoolKey-uint160-
:xref-ReHypothecationHook-seedLiquidity-uint256-uint256-: xref:general.adoc#ReHypothecationHook-seedLiquidity-uint256-uint256-
:xref-ReHypothecationHook-addReHypothecatedLiquidity-uint256-: xref:general.adoc#ReHypothecationHook-addReHypothecatedLiquidity-uint256-
:xref-ReHypothecationHook-removeReHypothecatedLiquidity-uint256-: xref:general.adoc#ReHypothecationHook-removeReHypothecatedLiquidity-uint256-
:xref-ReHypothecationHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:general.adoc#ReHypothecationHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-ReHypothecationHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:general.adoc#ReHypothecationHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-ReHypothecationHook-_resolveHookDelta-Currency-: xref:general.adoc#ReHypothecationHook-_resolveHookDelta-Currency-
:xref-ReHypothecationHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:general.adoc#ReHypothecationHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-ReHypothecationHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:general.adoc#ReHypothecationHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-ReHypothecationHook-previewMint-uint256-: xref:general.adoc#ReHypothecationHook-previewMint-uint256-
:xref-ReHypothecationHook-previewRedeem-uint256-: xref:general.adoc#ReHypothecationHook-previewRedeem-uint256-
:xref-ReHypothecationHook-_sharesToAmounts-uint256-enum-Math-Rounding-: xref:general.adoc#ReHypothecationHook-_sharesToAmounts-uint256-enum-Math-Rounding-
:xref-ReHypothecationHook-_shareToAmount-uint256-Currency-enum-Math-Rounding-: xref:general.adoc#ReHypothecationHook-_shareToAmount-uint256-Currency-enum-Math-Rounding-
:xref-ReHypothecationHook-_decimalsOffset--: xref:general.adoc#ReHypothecationHook-_decimalsOffset--
:xref-ReHypothecationHook-_getLiquidityToUse-int24-int24-: xref:general.adoc#ReHypothecationHook-_getLiquidityToUse-int24-int24-
:xref-ReHypothecationHook-_getHookPositionLiquidity--: xref:general.adoc#ReHypothecationHook-_getHookPositionLiquidity--
:xref-ReHypothecationHook-getTickLower--: xref:general.adoc#ReHypothecationHook-getTickLower--
:xref-ReHypothecationHook-getTickUpper--: xref:general.adoc#ReHypothecationHook-getTickUpper--
:xref-ReHypothecationHook-_modifyLiquidity-int256-: xref:general.adoc#ReHypothecationHook-_modifyLiquidity-int256-
:xref-ReHypothecationHook-_transferFromSenderToHook-Currency-uint256-address-: xref:general.adoc#ReHypothecationHook-_transferFromSenderToHook-Currency-uint256-address-
:xref-ReHypothecationHook-_transferFromHookToSender-Currency-uint256-address-: xref:general.adoc#ReHypothecationHook-_transferFromHookToSender-Currency-uint256-address-
:xref-ReHypothecationHook-getCurrencyYieldSource-Currency-: xref:general.adoc#ReHypothecationHook-getCurrencyYieldSource-Currency-
:xref-ReHypothecationHook-_depositToYieldSource-Currency-uint256-: xref:general.adoc#ReHypothecationHook-_depositToYieldSource-Currency-uint256-
:xref-ReHypothecationHook-_withdrawFromYieldSource-Currency-uint256-: xref:general.adoc#ReHypothecationHook-_withdrawFromYieldSource-Currency-uint256-
:xref-ReHypothecationHook-_getAmountInYieldSource-Currency-: xref:general.adoc#ReHypothecationHook-_getAmountInYieldSource-Currency-
:xref-ReHypothecationHook-_getMaxWithdrawFromYieldSource-Currency-: xref:general.adoc#ReHypothecationHook-_getMaxWithdrawFromYieldSource-Currency-
:xref-ReHypothecationHook-getHookPermissions--: xref:general.adoc#ReHypothecationHook-getHookPermissions--
:xref-ReHypothecationHook-receive--: xref:general.adoc#ReHypothecationHook-receive--
:xref-BaseHook-_validateHookAddress-contract-BaseHook-: xref:base.adoc#BaseHook-_validateHookAddress-contract-BaseHook-
:xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-: xref:base.adoc#BaseHook-beforeInitialize-address-struct-PoolKey-uint160-
:xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-: xref:base.adoc#BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-: xref:base.adoc#BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-
:xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-: xref:base.adoc#BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-
:xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-: xref:base.adoc#BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-
:xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-: xref:base.adoc#BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-
:xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-: xref:base.adoc#BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-
:xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-: xref:base.adoc#BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-
:xref-BaseHook-poolManager-contract-IPoolManager: xref:base.adoc#BaseHook-poolManager-contract-IPoolManager
:xref-ReHypothecationHook-ReHypothecatedLiquidityAdded-address-struct-PoolKey-uint256-uint256-uint256-: xref:general.adoc#ReHypothecationHook-ReHypothecatedLiquidityAdded-address-struct-PoolKey-uint256-uint256-uint256-
:xref-ReHypothecationHook-ReHypothecatedLiquidityRemoved-address-struct-PoolKey-uint256-uint256-uint256-: xref:general.adoc#ReHypothecationHook-ReHypothecatedLiquidityRemoved-address-struct-PoolKey-uint256-uint256-uint256-
:xref-ReHypothecationHook-AlreadyInitialized--: xref:general.adoc#ReHypothecationHook-AlreadyInitialized--
:xref-ReHypothecationHook-NotInitialized--: xref:general.adoc#ReHypothecationHook-NotInitialized--
:xref-ReHypothecationHook-ZeroShares--: xref:general.adoc#ReHypothecationHook-ZeroShares--
:xref-ReHypothecationHook-InvalidMsgValue--: xref:general.adoc#ReHypothecationHook-InvalidMsgValue--
:xref-ReHypothecationHook-RefundFailed--: xref:general.adoc#ReHypothecationHook-RefundFailed--
:xref-ReHypothecationHook-LiquidityNotAllowed--: xref:general.adoc#ReHypothecationHook-LiquidityNotAllowed--
:xref-ReHypothecationHook-NotSeeded--: xref:general.adoc#ReHypothecationHook-NotSeeded--
:xref-ReHypothecationHook-AlreadySeeded--: xref:general.adoc#ReHypothecationHook-AlreadySeeded--
:xref-ReHypothecationHook-InsufficientSeed-uint256-uint256-: xref:general.adoc#ReHypothecationHook-InsufficientSeed-uint256-uint256-
:xref-ReHypothecationHook-JITLocked--: xref:general.adoc#ReHypothecationHook-JITLocked--
:xref-BaseHook-HookNotImplemented--: xref:base.adoc#BaseHook-HookNotImplemented--
:xref-BaseHook-NotPoolManager--: xref:base.adoc#BaseHook-NotPoolManager--
:xref-BaseHook-InvalidPool--: xref:base.adoc#BaseHook-InvalidPool--
= General

[.readme-notice]
NOTE: This document is better viewed on the docs page.

Ready-to-use hooks built on top of the base and fee abstract contracts

 * {LiquidityPenaltyHook}: Hook resistant to just-in-time liquidity attacks
 * {AntiSandwichHook}: Hook resistant to sandwich attacks on swaps
 * {LimitOrderHook}: Hook to enable limit order placing on liquidity pools
 * {ReHypothecationHook}: Hook that enables rehypothecation of liquidity positions.

== Hooks

:BlockNumberOffsetTooLow: pass:normal[xref:#LiquidityPenaltyHook-BlockNumberOffsetTooLow--[`++BlockNumberOffsetTooLow++`]]
:NoLiquidityToReceiveDonation: pass:normal[xref:#LiquidityPenaltyHook-NoLiquidityToReceiveDonation--[`++NoLiquidityToReceiveDonation++`]]
:MIN_BLOCK_NUMBER_OFFSET: pass:normal[xref:#LiquidityPenaltyHook-MIN_BLOCK_NUMBER_OFFSET-uint48[`++MIN_BLOCK_NUMBER_OFFSET++`]]
:blockNumberOffset: pass:normal[xref:#LiquidityPenaltyHook-blockNumberOffset-uint48[`++blockNumberOffset++`]]
:constructor: pass:normal[xref:#LiquidityPenaltyHook-constructor-uint48-[`++constructor++`]]
:_afterAddLiquidity: pass:normal[xref:#LiquidityPenaltyHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-[`++_afterAddLiquidity++`]]
:_afterRemoveLiquidity: pass:normal[xref:#LiquidityPenaltyHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-[`++_afterRemoveLiquidity++`]]
:_getBlockNumber: pass:normal[xref:#LiquidityPenaltyHook-_getBlockNumber--[`++_getBlockNumber++`]]
:_updateLastAddedLiquidityBlock: pass:normal[xref:#LiquidityPenaltyHook-_updateLastAddedLiquidityBlock-PoolId-bytes32-[`++_updateLastAddedLiquidityBlock++`]]
:_takeFeesToHook: pass:normal[xref:#LiquidityPenaltyHook-_takeFeesToHook-struct-PoolKey-bytes32-BalanceDelta-[`++_takeFeesToHook++`]]
:_settleFeesFromHook: pass:normal[xref:#LiquidityPenaltyHook-_settleFeesFromHook-struct-PoolKey-bytes32-[`++_settleFeesFromHook++`]]
:_calculateLiquidityPenalty: pass:normal[xref:#LiquidityPenaltyHook-_calculateLiquidityPenalty-BalanceDelta-uint48-[`++_calculateLiquidityPenalty++`]]
:getLastAddedLiquidityBlock: pass:normal[xref:#LiquidityPenaltyHook-getLastAddedLiquidityBlock-PoolId-bytes32-[`++getLastAddedLiquidityBlock++`]]
:getWithheldFees: pass:normal[xref:#LiquidityPenaltyHook-getWithheldFees-PoolId-bytes32-[`++getWithheldFees++`]]
:getHookPermissions: pass:normal[xref:#LiquidityPenaltyHook-getHookPermissions--[`++getHookPermissions++`]]

[.contract]
[[LiquidityPenaltyHook]]
=== `++LiquidityPenaltyHook++` link:https://github.com/OpenZeppelin/uniswap-hooks/blob/master/src/general/LiquidityPenaltyHook.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import "uniswap-hooks/src/general/LiquidityPenaltyHook.sol";
```

Just-in-Time (JIT) liquidity provisioning resistant hook.

This hook disincentivizes JIT attacks by penalizing LP fee collection during {_afterRemoveLiquidity},
and disabling it during {_afterAddLiquidity} if liquidity was recently added to the position.
The penalty is donated to the pool's liquidity providers in range at the time of removal.

See {_calculateLiquidityPenalty} for penalty calculation.

NOTE: If a long term liquidity provider adds liquidity continuously, a pause of `blockNumberOffset`
before removing will be needed if `feesAccrued` collection is intended, in order to avoid getting
penalized by the JIT protection mechanism.

WARNING: Altrough this hook achieves it's objective of protecting long term LP's in most scenarios,
low liquidity pools and long-tail assets may still be vulnerable depending on the configured `blockNumberOffset`.
Larger values of such are recommended in those cases in order to decrease the profitability of the attack.

WARNING: In low liquidity pools, this hook may be vulnerable to multi-account strategies: attackers may bypass JIT protection
by using a secondary account to add minimal liquidity at a target tick with no other liquidity, then moving the price there after a JIT attack.
This allows penalty fees to be redirected to the attacker's secondary account. While technically feasible, this attack is rarely profitable in practice,
due to the cost associated with moving the price to the target tick.

WARNING: This is experimental software and is provided on an "as is" and "as available" basis. We do
not give any warranties and will not be liable for any losses incurred through any use of this code
base.

_Available since v0.1.1_

[.contract-index]
.Functions
--
* {xref-LiquidityPenaltyHook-constructor-uint48-}[`++constructor(_blockNumberOffset)++`]
* {xref-LiquidityPenaltyHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterAddLiquidity(sender, key, params, , feeDelta, )++`]
* {xref-LiquidityPenaltyHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterRemoveLiquidity(sender, key, params, , feeDelta, )++`]
* {xref-LiquidityPenaltyHook-_getBlockNumber--}[`++_getBlockNumber()++`]
* {xref-LiquidityPenaltyHook-_updateLastAddedLiquidityBlock-PoolId-bytes32-}[`++_updateLastAddedLiquidityBlock(poolId, positionKey)++`]
* {xref-LiquidityPenaltyHook-_takeFeesToHook-struct-PoolKey-bytes32-BalanceDelta-}[`++_takeFeesToHook(key, positionKey, feeDelta)++`]
* {xref-LiquidityPenaltyHook-_settleFeesFromHook-struct-PoolKey-bytes32-}[`++_settleFeesFromHook(key, positionKey)++`]
* {xref-LiquidityPenaltyHook-_calculateLiquidityPenalty-BalanceDelta-uint48-}[`++_calculateLiquidityPenalty(feeDelta, lastAddedLiquidityBlock)++`]
* {xref-LiquidityPenaltyHook-getLastAddedLiquidityBlock-PoolId-bytes32-}[`++getLastAddedLiquidityBlock(poolId, positionKey)++`]
* {xref-LiquidityPenaltyHook-getWithheldFees-PoolId-bytes32-}[`++getWithheldFees(poolId, positionKey)++`]
* {xref-LiquidityPenaltyHook-getHookPermissions--}[`++getHookPermissions()++`]
* {xref-LiquidityPenaltyHook-MIN_BLOCK_NUMBER_OFFSET-uint48}[`++MIN_BLOCK_NUMBER_OFFSET()++`]
* {xref-LiquidityPenaltyHook-blockNumberOffset-uint48}[`++blockNumberOffset()++`]

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-_validateHookAddress-contract-BaseHook-}[`++_validateHookAddress(hook)++`]
* {xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-}[`++beforeInitialize(sender, key, sqrtPriceX96)++`]
* {xref-BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-}[`++_beforeInitialize(, , )++`]
* {xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-}[`++afterInitialize(sender, key, sqrtPriceX96, tick)++`]
* {xref-BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-}[`++_afterInitialize(, , , )++`]
* {xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeAddLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeAddLiquidity(, , , )++`]
* {xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeRemoveLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeRemoveLiquidity(, , , )++`]
* {xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterAddLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterRemoveLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++beforeSwap(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++_beforeSwap(, , , )++`]
* {xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++afterSwap(sender, key, params, delta, hookData)++`]
* {xref-BaseHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++_afterSwap(, , , , )++`]
* {xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++beforeDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_beforeDonate(, , , , )++`]
* {xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++afterDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_afterDonate(, , , , )++`]
* {xref-BaseHook-poolManager-contract-IPoolManager}[`++poolManager()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Errors
--
* {xref-LiquidityPenaltyHook-BlockNumberOffsetTooLow--}[`++BlockNumberOffsetTooLow()++`]
* {xref-LiquidityPenaltyHook-NoLiquidityToReceiveDonation--}[`++NoLiquidityToReceiveDonation()++`]

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-HookNotImplemented--}[`++HookNotImplemented()++`]
* {xref-BaseHook-NotPoolManager--}[`++NotPoolManager()++`]
* {xref-BaseHook-InvalidPool--}[`++InvalidPool()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-item]
[[LiquidityPenaltyHook-constructor-uint48-]]
==== `[.contract-item-name]#++constructor++#++(uint48 _blockNumberOffset)++` [.item-kind]#internal#

Sets the {getBlockNumberOffset} and the {poolManager} address.

[.contract-item]
[[LiquidityPenaltyHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-]]
==== `[.contract-item-name]#++_afterAddLiquidity++#++(address sender, struct PoolKey key, struct ModifyLiquidityParams params, BalanceDelta, BalanceDelta feeDelta, bytes) → bytes4, BalanceDelta++` [.item-kind]#internal#

Tracks `lastAddedLiquidityBlock` and withholds `feeDelta` if liquidity was recently added within
the `blockNumberOffset` period.

See {_afterRemoveLiquidity} for claiming the withheld fees back.

[.contract-item]
[[LiquidityPenaltyHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-]]
==== `[.contract-item-name]#++_afterRemoveLiquidity++#++(address sender, struct PoolKey key, struct ModifyLiquidityParams params, BalanceDelta, BalanceDelta feeDelta, bytes) → bytes4, BalanceDelta++` [.item-kind]#internal#

Penalizes the collection of any existing LP `feesDelta` and `withheldFees` after liquidity removal if
liquidity was recently added to the position.

NOTE: The penalty is applied on both `withheldFees` and `feeDelta` equally.
Therefore, regardless of how many times liquidity was added to the position within the `blockNumberOffset` period,
all accrued fees are penalized as if the liquidity was added only once during that period. This ensures that
splitting liquidity additions within the `blockNumberOffset` period does not reduce or increase the penalty.

IMPORTANT: The penalty is donated to the pool's liquidity providers in range at the time of liquidity removal,
which may be different from the liquidity providers in range at the time of liquidity addition.

[.contract-item]
[[LiquidityPenaltyHook-_getBlockNumber--]]
==== `[.contract-item-name]#++_getBlockNumber++#++() → uint48++` [.item-kind]#internal#

Returns the current block number.

[.contract-item]
[[LiquidityPenaltyHook-_updateLastAddedLiquidityBlock-PoolId-bytes32-]]
==== `[.contract-item-name]#++_updateLastAddedLiquidityBlock++#++(PoolId poolId, bytes32 positionKey)++` [.item-kind]#internal#

Updates the `lastAddedLiquidityBlock` for a liquidity position.

[.contract-item]
[[LiquidityPenaltyHook-_takeFeesToHook-struct-PoolKey-bytes32-BalanceDelta-]]
==== `[.contract-item-name]#++_takeFeesToHook++#++(struct PoolKey key, bytes32 positionKey, BalanceDelta feeDelta)++` [.item-kind]#internal#

Takes `feeDelta` from a liquidity position as `withheldFees` into this hook.

[.contract-item]
[[LiquidityPenaltyHook-_settleFeesFromHook-struct-PoolKey-bytes32-]]
==== `[.contract-item-name]#++_settleFeesFromHook++#++(struct PoolKey key, bytes32 positionKey) → BalanceDelta withheldFees++` [.item-kind]#internal#

Returns `withheldFees` from this hook to the liquidity provider.

[.contract-item]
[[LiquidityPenaltyHook-_calculateLiquidityPenalty-BalanceDelta-uint48-]]
==== `[.contract-item-name]#++_calculateLiquidityPenalty++#++(BalanceDelta feeDelta, uint48 lastAddedLiquidityBlock) → BalanceDelta liquidityPenalty++` [.item-kind]#internal#

Calculates the penalty to be applied to JIT liquidity provisioning.

The penalty is calculated as a linear function of the block number difference between the `lastAddedLiquidityBlock` and the `currentBlockNumber`.

The used formula is:

liquidityPenalty = feeDelta * ( 1 - (currentBlockNumber - lastAddedLiquidityBlock) / blockNumberOffset)

As a result, the penalty is 100% at the same block where liquidity was last added and zero after the `blockNumberOffset` block time window.

NOTE: Won't overflow if `currentBlockNumber - lastAddedLiquidityBlock < blockNumberOffset` is verified prior to calling this function.

[.contract-item]
[[LiquidityPenaltyHook-getLastAddedLiquidityBlock-PoolId-bytes32-]]
==== `[.contract-item-name]#++getLastAddedLiquidityBlock++#++(PoolId poolId, bytes32 positionKey) → uint48++` [.item-kind]#public#

Tracks the `lastAddedLiquidityBlock` for a liquidity position.

`lastAddedLiquidityBlock` is the block number when liquidity was last added to the position.

[.contract-item]
[[LiquidityPenaltyHook-getWithheldFees-PoolId-bytes32-]]
==== `[.contract-item-name]#++getWithheldFees++#++(PoolId poolId, bytes32 positionKey) → BalanceDelta++` [.item-kind]#public#

Returns the `withheldFees` for a liquidity position.

`withheldFees` are UniswapV4's `feesAccrued` retained by this hook during liquidity addition if liquidity
has been recently added within the `blockNumberOffset` block time window, with the purpose of disabling fee
collection during JIT liquidity provisioning attacks. See {_afterRemoveLiquidity} for claiming the fees back.

[.contract-item]
[[LiquidityPenaltyHook-getHookPermissions--]]
==== `[.contract-item-name]#++getHookPermissions++#++() → struct Hooks.Permissions permissions++` [.item-kind]#public#

Set the hooks permissions, specifically `afterAddLiquidity`, `afterAddLiquidityReturnDelta`, `afterRemoveLiquidity` and `afterRemoveLiquidityReturnDelta`.

[.contract-item]
[[LiquidityPenaltyHook-MIN_BLOCK_NUMBER_OFFSET-uint48]]
==== `[.contract-item-name]#++MIN_BLOCK_NUMBER_OFFSET++#++() → uint48++` [.item-kind]#public#

The minimum value for the {blockNumberOffset}.

[.contract-item]
[[LiquidityPenaltyHook-blockNumberOffset-uint48]]
==== `[.contract-item-name]#++blockNumberOffset++#++() → uint48++` [.item-kind]#public#

The minimum time window (in blocks) that must pass after adding liquidity before it can be
removed without any penalty. During this period, JIT attacks are deterred through fee withholding
and penalties. Higher values provide stronger JIT protection but may discourage legitimate LPs.

[.contract-item]
[[LiquidityPenaltyHook-BlockNumberOffsetTooLow--]]
==== `[.contract-item-name]#++BlockNumberOffsetTooLow++#++()++` [.item-kind]#error#

The hook was attempted to be constructed with a `blockNumberOffset` lower than `MIN_BLOCK_NUMBER_OFFSET`.

[.contract-item]
[[LiquidityPenaltyHook-NoLiquidityToReceiveDonation--]]
==== `[.contract-item-name]#++NoLiquidityToReceiveDonation++#++()++` [.item-kind]#error#

A penalty was attempted to be applied and donated to LP's in range, but there aren't any.

:CheckpointNotSet: pass:normal[xref:#AntiSandwichHook-CheckpointNotSet--[`++CheckpointNotSet++`]]
:TargetOutOfRange: pass:normal[xref:#AntiSandwichHook-TargetOutOfRange--[`++TargetOutOfRange++`]]
:Checkpoint: pass:normal[xref:#AntiSandwichHook-Checkpoint[`++Checkpoint++`]]
:_beforeSwap: pass:normal[xref:#AntiSandwichHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-[`++_beforeSwap++`]]
:_getBlockNumber: pass:normal[xref:#AntiSandwichHook-_getBlockNumber--[`++_getBlockNumber++`]]
:getLastCheckpoint: pass:normal[xref:#AntiSandwichHook-getLastCheckpoint-PoolId-[`++getLastCheckpoint++`]]
:_getTargetUnspecified: pass:normal[xref:#AntiSandwichHook-_getTargetUnspecified-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-[`++_getTargetUnspecified++`]]
:getHookPermissions: pass:normal[xref:#AntiSandwichHook-getHookPermissions--[`++getHookPermissions++`]]

[.contract]
[[AntiSandwichHook]]
=== `++AntiSandwichHook++` link:https://github.com/OpenZeppelin/uniswap-hooks/blob/master/src/general/AntiSandwichHook.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import "uniswap-hooks/src/general/AntiSandwichHook.sol";
```

This hook is inspired by the sandwich-resistant AMM design introduced
https://www.umbraresearch.xyz/writings/sandwich-resistant-amm[here]. Specifically,
this hook guarantees that no swaps get filled at a price better than the price at
the beginning of the slot window (i.e. one block), up to rounding.

That price is recorded at the block's first swap, and any excess a later swap gains over it is taken as a
hook fee. A sandwich therefore closes no better than the price its opening leg moved away from, so it cannot
turn a profit.

In order to use this hook, the inheriting contract must implement the {_afterSwapHandler} function
to determine how to handle the collected fees from the anti-sandwich mechanism.

NOTE: The price is read at the block's first swap, which is the price the block opened with: in Uniswap v4
only a swap moves it, so liquidity changes and donations landing earlier in the block doesn't.

NOTE: A block whose price moved far is expensive for everyone trading in it afterwards, since they are all
held to the opening price.

NOTE: The hook only takes, it never pays. A swap filled better than the recorded price has the
difference taken as a fee, while a swap filled worse keeps that fill and receives nothing. A swapper whose
fill was worsened, by liquidity withdrawn after the block's first swap for example, is not compensated:
the mechanism removes an attacker's profit rather than restoring a victim's loss.

NOTE: Only swaps are bounded. An attacker can supply the liquidity a victim trades through and
withdraw it in the same block, and an attack whose legs sit in different blocks is measured against a
price its own opening leg set. Consider combining with a JIT protection mechanism such as
https://github.com/OpenZeppelin/uniswap-hooks/blob/master/src/general/LiquidityPenaltyHook.sol[LiquidityPenaltyHook].

IMPORTANT: {TargetOutOfRange} refuses a swap that would owe more than a `BalanceDelta` holds, rather than
charge it nothing. Reaching it needs the price to cross most of the tick range inside one block, which
needs liquidity thin enough for a single swap to do that. Consider how widely liquidity is provided before
deploying.

IMPORTANT: The fee is a sandwich's own gain, so {_afterSwapHandler} must not pay it to in-range liquidity.
An attacker can supply that liquidity and collect the fee back, whether it is paid in the same block or a
later one.

WARNING: A price move made inside a block is not corrected inside it, since a correcting trade and a
sandwich's closing leg are the same trade. Correction waits for the next block, where the checkpoint has
reset to the moved price and trading away from it is free. Arbitrage is delayed a block, not discouraged.

WARNING: This is experimental software and is provided on an "as is" and "as available" basis. We do
not give any warranties and will not be liable for any losses incurred through any use of this code
base.

_Available since v1.1.0_

[.contract-index]
.Functions
--
* {xref-AntiSandwichHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++_beforeSwap(, key, , )++`]
* {xref-AntiSandwichHook-_getBlockNumber--}[`++_getBlockNumber()++`]
* {xref-AntiSandwichHook-getLastCheckpoint-PoolId-}[`++getLastCheckpoint(poolId)++`]
* {xref-AntiSandwichHook-_getTargetUnspecified-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++_getTargetUnspecified(, key, params, delta, )++`]
* {xref-AntiSandwichHook-getHookPermissions--}[`++getHookPermissions()++`]

[.contract-subindex-inherited]
.BaseDynamicAfterFee
* {xref-BaseDynamicAfterFee-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++_afterSwap(sender, key, params, delta, hookData)++`]
* {xref-BaseDynamicAfterFee-_afterSwapHandler-struct-PoolKey-struct-SwapParams-BalanceDelta-uint256-uint256-}[`++_afterSwapHandler(key, params, delta, targetUnspecifiedAmount, feeAmount)++`]

[.contract-subindex-inherited]
.IHookEvents

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-_validateHookAddress-contract-BaseHook-}[`++_validateHookAddress(hook)++`]
* {xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-}[`++beforeInitialize(sender, key, sqrtPriceX96)++`]
* {xref-BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-}[`++_beforeInitialize(, , )++`]
* {xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-}[`++afterInitialize(sender, key, sqrtPriceX96, tick)++`]
* {xref-BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-}[`++_afterInitialize(, , , )++`]
* {xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeAddLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeAddLiquidity(, , , )++`]
* {xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeRemoveLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeRemoveLiquidity(, , , )++`]
* {xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterAddLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterAddLiquidity(, , , , , )++`]
* {xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterRemoveLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterRemoveLiquidity(, , , , , )++`]
* {xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++beforeSwap(sender, key, params, hookData)++`]
* {xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++afterSwap(sender, key, params, delta, hookData)++`]
* {xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++beforeDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_beforeDonate(, , , , )++`]
* {xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++afterDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_afterDonate(, , , , )++`]
* {xref-BaseHook-poolManager-contract-IPoolManager}[`++poolManager()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Events
--

[.contract-subindex-inherited]
.BaseDynamicAfterFee

[.contract-subindex-inherited]
.IHookEvents
* {xref-IHookEvents-HookSwap-bytes32-address-int128-int128-uint128-uint128-}[`++HookSwap(poolId, sender, amount0, amount1, hookLPfeeAmount0, hookLPfeeAmount1)++`]
* {xref-IHookEvents-HookFee-bytes32-address-uint128-uint128-}[`++HookFee(poolId, sender, feeAmount0, feeAmount1)++`]
* {xref-IHookEvents-HookModifyLiquidity-bytes32-address-int128-int128-}[`++HookModifyLiquidity(poolId, sender, amount0, amount1)++`]
* {xref-IHookEvents-HookBonus-bytes32-uint128-uint128-}[`++HookBonus(poolId, amount0, amount1)++`]

[.contract-subindex-inherited]
.BaseHook

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Errors
--
* {xref-AntiSandwichHook-CheckpointNotSet--}[`++CheckpointNotSet()++`]
* {xref-AntiSandwichHook-TargetOutOfRange--}[`++TargetOutOfRange()++`]

[.contract-subindex-inherited]
.BaseDynamicAfterFee

[.contract-subindex-inherited]
.IHookEvents

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-HookNotImplemented--}[`++HookNotImplemented()++`]
* {xref-BaseHook-NotPoolManager--}[`++NotPoolManager()++`]
* {xref-BaseHook-InvalidPool--}[`++InvalidPool()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-item]
[[AntiSandwichHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-]]
==== `[.contract-item-name]#++_beforeSwap++#++(address, struct PoolKey key, struct SwapParams, bytes) → bytes4, BeforeSwapDelta, uint24++` [.item-kind]#internal#

Records the pool price at the block's first swap. Later swaps in the block leave it untouched.

[.contract-item]
[[AntiSandwichHook-_getBlockNumber--]]
==== `[.contract-item-name]#++_getBlockNumber++#++() → uint48++` [.item-kind]#internal#

Returns the block a swap belongs to.

IMPORTANT: An override must return one value per block and a different one in the next. A value that
moves within a block re-records the price on every swap, which removes the protection. One that never
moves anchors the pool to a single price. Both fail silently.

[.contract-item]
[[AntiSandwichHook-getLastCheckpoint-PoolId-]]
==== `[.contract-item-name]#++getLastCheckpoint++#++(PoolId poolId) → struct AntiSandwichHook.Checkpoint++` [.item-kind]#public#

Returns the checkpoint `poolId` holds. A pool never swapped in holds a zero one.

[.contract-item]
[[AntiSandwichHook-_getTargetUnspecified-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-]]
==== `[.contract-item-name]#++_getTargetUnspecified++#++(address, struct PoolKey key, struct SwapParams params, BalanceDelta delta, bytes) → uint256 targetUnspecifiedAmount, bool applyTarget++` [.item-kind]#internal#

Returns the target `delta` is held to, and whether it applies.

The unspecified side carries the target, so an exact input reads it as a ceiling on what the swap keeps
and an exact output as a floor on what it pays. {BaseDynamicAfterFee-_afterSwap} takes the difference
either way.

Every rounding favors the swapper, so a swap that did not beat the recorded price is never charged. The
target is loose by the conversion's resolution in exchange, which grows with the price but never with
the size of a swap, while the slippage a sandwich pays to open grows with its size.

NOTE: No fee is taken where the target is a ceiling past what a `BalanceDelta` carries, and that
changes nothing: such a ceiling already sits above every amount the swap could have received. The same
overflow on a floor does bind, and reverts rather than charging nothing.

[.contract-item]
[[AntiSandwichHook-getHookPermissions--]]
==== `[.contract-item-name]#++getHookPermissions++#++() → struct Hooks.Permissions permissions++` [.item-kind]#public#

Set the hook permissions, specifically `beforeSwap`, `afterSwap`, and `afterSwapReturnDelta`.

[.contract-item]
[[AntiSandwichHook-CheckpointNotSet--]]
==== `[.contract-item-name]#++CheckpointNotSet++#++()++` [.item-kind]#error#

A swap ran against a pool holding no beginning-of-block price to hold it to.

[.contract-item]
[[AntiSandwichHook-TargetOutOfRange--]]
==== `[.contract-item-name]#++TargetOutOfRange++#++()++` [.item-kind]#error#

The swap would owe more than a `BalanceDelta` holds, so it cannot be charged what it owes.

:OrderInfo: pass:normal[xref:#LimitOrderHook-OrderInfo[`++OrderInfo++`]]
:UserInfo: pass:normal[xref:#LimitOrderHook-UserInfo[`++UserInfo++`]]
:CallbackType: pass:normal[xref:#LimitOrderHook-CallbackType[`++CallbackType++`]]
:CallbackData: pass:normal[xref:#LimitOrderHook-CallbackData[`++CallbackData++`]]
:PlaceCallbackData: pass:normal[xref:#LimitOrderHook-PlaceCallbackData[`++PlaceCallbackData++`]]
:CancelCallbackData: pass:normal[xref:#LimitOrderHook-CancelCallbackData[`++CancelCallbackData++`]]
:WithdrawCallbackData: pass:normal[xref:#LimitOrderHook-WithdrawCallbackData[`++WithdrawCallbackData++`]]
:ZERO_BYTES: pass:normal[xref:#LimitOrderHook-ZERO_BYTES-bytes[`++ZERO_BYTES++`]]
:ORDER_ID_DEFAULT: pass:normal[xref:#LimitOrderHook-ORDER_ID_DEFAULT-OrderIdLibrary-OrderId[`++ORDER_ID_DEFAULT++`]]
:ZeroLiquidity: pass:normal[xref:#LimitOrderHook-ZeroLiquidity--[`++ZeroLiquidity++`]]
:InRange: pass:normal[xref:#LimitOrderHook-InRange--[`++InRange++`]]
:CrossedRange: pass:normal[xref:#LimitOrderHook-CrossedRange--[`++CrossedRange++`]]
:Filled: pass:normal[xref:#LimitOrderHook-Filled--[`++Filled++`]]
:NotFilled: pass:normal[xref:#LimitOrderHook-NotFilled--[`++NotFilled++`]]
:NativeCurrencyUnsupported: pass:normal[xref:#LimitOrderHook-NativeCurrencyUnsupported--[`++NativeCurrencyUnsupported++`]]
:Place: pass:normal[xref:#LimitOrderHook-Place-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-[`++Place++`]]
:Fill: pass:normal[xref:#LimitOrderHook-Fill-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-[`++Fill++`]]
:Cancel: pass:normal[xref:#LimitOrderHook-Cancel-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-[`++Cancel++`]]
:Withdraw: pass:normal[xref:#LimitOrderHook-Withdraw-address-OrderIdLibrary-OrderId-uint128-[`++Withdraw++`]]
:_afterInitialize: pass:normal[xref:#LimitOrderHook-_afterInitialize-address-struct-PoolKey-uint160-int24-[`++_afterInitialize++`]]
:_afterSwap: pass:normal[xref:#LimitOrderHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-[`++_afterSwap++`]]
:placeOrder: pass:normal[xref:#LimitOrderHook-placeOrder-struct-PoolKey-int24-bool-uint128-[`++placeOrder++`]]
:cancelOrder: pass:normal[xref:#LimitOrderHook-cancelOrder-struct-PoolKey-int24-bool-address-[`++cancelOrder++`]]
:withdraw: pass:normal[xref:#LimitOrderHook-withdraw-OrderIdLibrary-OrderId-address-[`++withdraw++`]]
:unlockCallback: pass:normal[xref:#LimitOrderHook-unlockCallback-bytes-[`++unlockCallback++`]]
:_handlePlaceCallback: pass:normal[xref:#LimitOrderHook-_handlePlaceCallback-struct-LimitOrderHook-PlaceCallbackData-[`++_handlePlaceCallback++`]]
:_handleCancelCallback: pass:normal[xref:#LimitOrderHook-_handleCancelCallback-struct-LimitOrderHook-CancelCallbackData-[`++_handleCancelCallback++`]]
:_handleWithdrawCallback: pass:normal[xref:#LimitOrderHook-_handleWithdrawCallback-struct-LimitOrderHook-WithdrawCallbackData-[`++_handleWithdrawCallback++`]]
:_fillCrossedOrders: pass:normal[xref:#LimitOrderHook-_fillCrossedOrders-struct-PoolKey-bool-[`++_fillCrossedOrders++`]]
:_fillOrder: pass:normal[xref:#LimitOrderHook-_fillOrder-struct-PoolKey-int24-bool-[`++_fillOrder++`]]
:_getCrossedTicks: pass:normal[xref:#LimitOrderHook-_getCrossedTicks-PoolId-int24-[`++_getCrossedTicks++`]]
:_getTickLower: pass:normal[xref:#LimitOrderHook-_getTickLower-int24-int24-[`++_getTickLower++`]]
:_getCurrentTick: pass:normal[xref:#LimitOrderHook-_getCurrentTick-PoolId-[`++_getCurrentTick++`]]
:_getPositionSalt: pass:normal[xref:#LimitOrderHook-_getPositionSalt-bool-[`++_getPositionSalt++`]]
:getTickLowerLast: pass:normal[xref:#LimitOrderHook-getTickLowerLast-PoolId-[`++getTickLowerLast++`]]
:getOrderId: pass:normal[xref:#LimitOrderHook-getOrderId-struct-PoolKey-int24-bool-[`++getOrderId++`]]
:getOrderInfo: pass:normal[xref:#LimitOrderHook-getOrderInfo-OrderIdLibrary-OrderId-[`++getOrderInfo++`]]
:getUserInfo: pass:normal[xref:#LimitOrderHook-getUserInfo-OrderIdLibrary-OrderId-address-[`++getUserInfo++`]]
:getHookPermissions: pass:normal[xref:#LimitOrderHook-getHookPermissions--[`++getHookPermissions++`]]

[.contract]
[[LimitOrderHook]]
=== `++LimitOrderHook++` link:https://github.com/OpenZeppelin/uniswap-hooks/blob/master/src/general/LimitOrderHook.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import "uniswap-hooks/src/general/LimitOrderHook.sol";
```

Limit Order Mechanism hook.

Allows users to place limit orders at specific ticks the price has not yet crossed,
which will be filled if the pool's price crosses the order's tick.

Note that given the way UniswapV4 pools works, when liquidity is added out of the current range,
a single currency will be provided, instead of both currencies as in in-range liquidity additions.

Orders can be cancelled at any time until they are filled and their liquidity is removed from the pool.
Once completely filled, the resulting liquidity can be withdrawn from the pool.

NOTE: Fees accrued by an order are credited per unit of liquidity, so each owner is entitled to the
fees earned while its liquidity was in the order and to none of those earned before it. Amounts are truncated
in the order's favour, so a negligible residual can remain in the hook.

NOTE: Native currency orders are not supported.

IMPORTANT: Uniswap V4 does not call a hook's own callbacks when that hook is the caller, so {_afterSwap}
does not run for a swap this hook makes itself. A subclass that swaps internally MUST call
{_fillCrossedOrders} afterwards, or the tick recorded for the pool falls behind the price and the next
crossing is measured from it.

WARNING: This is experimental software and is provided on an "as is" and "as available" basis. We do
not give any warranties and will not be liable for any losses incurred through any use of this code
base.

_Available since v1.1.0_

[.contract-index]
.Functions
--
* {xref-LimitOrderHook-_afterInitialize-address-struct-PoolKey-uint160-int24-}[`++_afterInitialize(, key, , tick)++`]
* {xref-LimitOrderHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++_afterSwap(, key, params, , )++`]
* {xref-LimitOrderHook-placeOrder-struct-PoolKey-int24-bool-uint128-}[`++placeOrder(key, tick, zeroForOne, liquidity)++`]
* {xref-LimitOrderHook-cancelOrder-struct-PoolKey-int24-bool-address-}[`++cancelOrder(key, tickLower, zeroForOne, to)++`]
* {xref-LimitOrderHook-withdraw-OrderIdLibrary-OrderId-address-}[`++withdraw(orderId, to)++`]
* {xref-LimitOrderHook-unlockCallback-bytes-}[`++unlockCallback(rawData)++`]
* {xref-LimitOrderHook-_handlePlaceCallback-struct-LimitOrderHook-PlaceCallbackData-}[`++_handlePlaceCallback(placeData)++`]
* {xref-LimitOrderHook-_handleCancelCallback-struct-LimitOrderHook-CancelCallbackData-}[`++_handleCancelCallback(cancelData)++`]
* {xref-LimitOrderHook-_handleWithdrawCallback-struct-LimitOrderHook-WithdrawCallbackData-}[`++_handleWithdrawCallback(withdrawData)++`]
* {xref-LimitOrderHook-_fillCrossedOrders-struct-PoolKey-bool-}[`++_fillCrossedOrders(key, swapZeroForOne)++`]
* {xref-LimitOrderHook-_fillOrder-struct-PoolKey-int24-bool-}[`++_fillOrder(key, tickLower, zeroForOne)++`]
* {xref-LimitOrderHook-_getCrossedTicks-PoolId-int24-}[`++_getCrossedTicks(poolId, tickSpacing)++`]
* {xref-LimitOrderHook-_getTickLower-int24-int24-}[`++_getTickLower(tick, tickSpacing)++`]
* {xref-LimitOrderHook-_getCurrentTick-PoolId-}[`++_getCurrentTick(poolId)++`]
* {xref-LimitOrderHook-_getPositionSalt-bool-}[`++_getPositionSalt(zeroForOne)++`]
* {xref-LimitOrderHook-getTickLowerLast-PoolId-}[`++getTickLowerLast(poolId)++`]
* {xref-LimitOrderHook-getOrderId-struct-PoolKey-int24-bool-}[`++getOrderId(key, tickLower, zeroForOne)++`]
* {xref-LimitOrderHook-getOrderInfo-OrderIdLibrary-OrderId-}[`++getOrderInfo(orderId)++`]
* {xref-LimitOrderHook-getUserInfo-OrderIdLibrary-OrderId-address-}[`++getUserInfo(orderId, owner)++`]
* {xref-LimitOrderHook-getHookPermissions--}[`++getHookPermissions()++`]

[.contract-subindex-inherited]
.IUnlockCallback

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-_validateHookAddress-contract-BaseHook-}[`++_validateHookAddress(hook)++`]
* {xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-}[`++beforeInitialize(sender, key, sqrtPriceX96)++`]
* {xref-BaseHook-_beforeInitialize-address-struct-PoolKey-uint160-}[`++_beforeInitialize(, , )++`]
* {xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-}[`++afterInitialize(sender, key, sqrtPriceX96, tick)++`]
* {xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeAddLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeAddLiquidity(, , , )++`]
* {xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeRemoveLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeRemoveLiquidity(, , , )++`]
* {xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterAddLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterAddLiquidity(, , , , , )++`]
* {xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterRemoveLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterRemoveLiquidity(, , , , , )++`]
* {xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++beforeSwap(sender, key, params, hookData)++`]
* {xref-BaseHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++_beforeSwap(, , , )++`]
* {xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++afterSwap(sender, key, params, delta, hookData)++`]
* {xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++beforeDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_beforeDonate(, , , , )++`]
* {xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++afterDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_afterDonate(, , , , )++`]
* {xref-BaseHook-poolManager-contract-IPoolManager}[`++poolManager()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Events
--
* {xref-LimitOrderHook-Place-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-}[`++Place(owner, orderId, key, tickLower, zeroForOne, liquidity)++`]
* {xref-LimitOrderHook-Fill-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-}[`++Fill(orderId, key, tickLower, zeroForOne)++`]
* {xref-LimitOrderHook-Cancel-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-}[`++Cancel(owner, orderId, key, tickLower, zeroForOne, liquidity)++`]
* {xref-LimitOrderHook-Withdraw-address-OrderIdLibrary-OrderId-uint128-}[`++Withdraw(owner, orderId, liquidity)++`]

[.contract-subindex-inherited]
.IUnlockCallback

[.contract-subindex-inherited]
.BaseHook

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Errors
--
* {xref-LimitOrderHook-ZeroLiquidity--}[`++ZeroLiquidity()++`]
* {xref-LimitOrderHook-InRange--}[`++InRange()++`]
* {xref-LimitOrderHook-CrossedRange--}[`++CrossedRange()++`]
* {xref-LimitOrderHook-Filled--}[`++Filled()++`]
* {xref-LimitOrderHook-NotFilled--}[`++NotFilled()++`]
* {xref-LimitOrderHook-NativeCurrencyUnsupported--}[`++NativeCurrencyUnsupported()++`]

[.contract-subindex-inherited]
.IUnlockCallback

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-HookNotImplemented--}[`++HookNotImplemented()++`]
* {xref-BaseHook-NotPoolManager--}[`++NotPoolManager()++`]
* {xref-BaseHook-InvalidPool--}[`++InvalidPool()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Internal Variables
--
* {xref-LimitOrderHook-ZERO_BYTES-bytes}[`++bytes constant ZERO_BYTES++`]
* {xref-LimitOrderHook-ORDER_ID_DEFAULT-OrderIdLibrary-OrderId}[`++OrderIdLibrary.OrderId constant ORDER_ID_DEFAULT++`]

[.contract-subindex-inherited]
.IUnlockCallback

[.contract-subindex-inherited]
.BaseHook

[.contract-subindex-inherited]
.IHooks

--

[.contract-item]
[[LimitOrderHook-_afterInitialize-address-struct-PoolKey-uint160-int24-]]
==== `[.contract-item-name]#++_afterInitialize++#++(address, struct PoolKey key, uint160, int24 tick) → bytes4++` [.item-kind]#internal#

Hooks into the `afterInitialize` hook to set the last tick lower for the pool.

[.contract-item]
[[LimitOrderHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-]]
==== `[.contract-item-name]#++_afterSwap++#++(address, struct PoolKey key, struct SwapParams params, BalanceDelta, bytes) → bytes4, int128++` [.item-kind]#internal#

Hooks into the `afterSwap` hook to fill the orders the swap crossed.

[.contract-item]
[[LimitOrderHook-placeOrder-struct-PoolKey-int24-bool-uint128-]]
==== `[.contract-item-name]#++placeOrder++#++(struct PoolKey key, int24 tick, bool zeroForOne, uint128 liquidity)++` [.item-kind]#public#

Places a limit order by adding liquidity out of range at a specific tick. The order will be filled when the
pool price crosses the specified `tick`. Takes a `PoolKey` `key`, target `tick`, direction `zeroForOne` indicating
whether to buy currency0 or currency1, and amount of `liquidity` to place. The interaction with the `poolManager` is done
via the `unlock` function, which will trigger the `{unlockCallback}` function.

Requirements:

- `key` must identify a pool configured with this hook, otherwise the order could never be filled.
- The placement must require only the currency being sold, otherwise it reverts {InRange}.

[.contract-item]
[[LimitOrderHook-cancelOrder-struct-PoolKey-int24-bool-address-]]
==== `[.contract-item-name]#++cancelOrder++#++(struct PoolKey key, int24 tickLower, bool zeroForOne, address to)++` [.item-kind]#public#

Cancels a limit order by removing liquidity from the pool. Takes a `PoolKey` `key`, `tickLower` of the order,
direction `zeroForOne` indicating whether it was buying currency0 or currency1, and recipient address `to` for the
removed liquidity. Note that partial cancellation is not supported - the entire liquidity added by the msg.sender will be removed.
Note also that cancelling an order will cancel the order placed by the msg.sender, not orders placed by other users in the same tick range.
The interaction with the `poolManager` is done via the `unlock` function, which will trigger the `{unlockCallback}` function.

Requirements:

- `key` must identify a pool configured with this hook.

[.contract-item]
[[LimitOrderHook-withdraw-OrderIdLibrary-OrderId-address-]]
==== `[.contract-item-name]#++withdraw++#++(OrderIdLibrary.OrderId orderId, address to) → uint256 amount0, uint256 amount1++` [.item-kind]#public#

Withdraws liquidity from a filled order, sending it to address `to`. Takes an `OrderId` `orderId` of the filled
order to withdraw from. Returns the withdrawn amounts as `(amount0, amount1)`. Can only be called after the order is
filled - use `cancelOrder` to remove liquidity from unfilled orders. The interaction with the `poolManager` is done via the
`unlock` function, which will trigger the `{unlockCallback}` function.

[.contract-item]
[[LimitOrderHook-unlockCallback-bytes-]]
==== `[.contract-item-name]#++unlockCallback++#++(bytes rawData) → bytes returnData++` [.item-kind]#public#

Handles callbacks from the `PoolManager` for order operations. Takes encoded `rawData` containing the callback type
and operation-specific data. Only callable by the PoolManager.

[.contract-item]
[[LimitOrderHook-_handlePlaceCallback-struct-LimitOrderHook-PlaceCallbackData-]]
==== `[.contract-item-name]#++_handlePlaceCallback++#++(struct LimitOrderHook.PlaceCallbackData placeData)++` [.item-kind]#internal#

Internal handler for place order callbacks. Takes `placeData` containing the order details, adds the
specified liquidity to the pool out of range and credits it to the owner. Reverts if the order would be
placed in range or on the wrong side of the range.

The fees the position accrued before this placement are credited to the owners already in the order, so
that the placer is not entitled to them.

[.contract-item]
[[LimitOrderHook-_handleCancelCallback-struct-LimitOrderHook-CancelCallbackData-]]
==== `[.contract-item-name]#++_handleCancelCallback++#++(struct LimitOrderHook.CancelCallbackData cancelData)++` [.item-kind]#internal#

Internal handler for cancel order callbacks. Takes `cancelData` containing the cancellation details,
removes the owner's liquidity from the pool and sends both its principal and the fees it is owed to the
recipient.

The fees the position accrued up to the removal are credited over the liquidity that earned them, which
still includes the cancelling owner's, so that owner is paid its share of them and nothing is left behind.

[.contract-item]
[[LimitOrderHook-_handleWithdrawCallback-struct-LimitOrderHook-WithdrawCallbackData-]]
==== `[.contract-item-name]#++_handleWithdrawCallback++#++(struct LimitOrderHook.WithdrawCallbackData withdrawData) → uint256 amount0, uint256 amount1++` [.item-kind]#internal#

Internal handler for withdraw callbacks. Takes `withdrawData` containing the withdrawal details, removes
the owner's liquidity from the order and sends its share of the principal and the fees it is owed to the
recipient. Returns the amounts sent.

The order is filled, so its liquidity was already removed from the pool and the amounts come from the claims
the hook holds.

[.contract-item]
[[LimitOrderHook-_fillCrossedOrders-struct-PoolKey-bool-]]
==== `[.contract-item-name]#++_fillCrossedOrders++#++(struct PoolKey key, bool swapZeroForOne)++` [.item-kind]#internal#

Fills the orders the price crossed since the tick last recorded for `key`, and records the tick
it reached. `swapZeroForOne` is the swap's direction, not the filled orders'.

IMPORTANT: A subclass that swaps inside its own unlock callback must call this afterwards, since the
pool does not report such a swap.

[.contract-item]
[[LimitOrderHook-_fillOrder-struct-PoolKey-int24-bool-]]
==== `[.contract-item-name]#++_fillOrder++#++(struct PoolKey key, int24 tickLower, bool zeroForOne)++` [.item-kind]#internal#

Internal handler for filling limit orders when price crosses a tick. Takes a `PoolKey` `key`, target `tickLower`,
and direction `zeroForOne`. Removes liquidity from filled orders, mints the received currencies to the hook, and
updates order state to track filled amounts.

[.contract-item]
[[LimitOrderHook-_getCrossedTicks-PoolId-int24-]]
==== `[.contract-item-name]#++_getCrossedTicks++#++(PoolId poolId, int24 tickSpacing) → int24 tickLower, int24 lower, int24 upper++` [.item-kind]#internal#

Internal helper that calculates the range of ticks crossed during a price change. Takes a `PoolId` `poolId`
and `tickSpacing`, returns the current `tickLower` and the range of ticks crossed (`lower`, `upper`) that need
to be checked for limit orders.

[.contract-item]
[[LimitOrderHook-_getTickLower-int24-int24-]]
==== `[.contract-item-name]#++_getTickLower++#++(int24 tick, int24 tickSpacing) → int24++` [.item-kind]#internal#

Get the tick lower. Takes a `tick` and `tickSpacing` and returns the nearest valid tick boundary
at or below the input tick, accounting for negative tick handling.

[.contract-item]
[[LimitOrderHook-_getCurrentTick-PoolId-]]
==== `[.contract-item-name]#++_getCurrentTick++#++(PoolId poolId) → int24 tick++` [.item-kind]#internal#

Get the current tick for a given pool. Takes a `PoolId` `poolId` and returns the tick the pool
stores, which is what marks whether a range is still active.

[.contract-item]
[[LimitOrderHook-_getPositionSalt-bool-]]
==== `[.contract-item-name]#++_getPositionSalt++#++(bool zeroForOne) → bytes32++` [.item-kind]#internal#

Returns the salt of the pool position backing an order in direction `zeroForOne`. Both
directions at one tick span the same range, so the salt is what keeps them in separate positions.

IMPORTANT: This value is part of a pool position's identity. Changing it on a deployed instance
strands the liquidity of every live order placed under the previous value.

[.contract-item]
[[LimitOrderHook-getTickLowerLast-PoolId-]]
==== `[.contract-item-name]#++getTickLowerLast++#++(PoolId poolId) → int24++` [.item-kind]#public#

Returns the last recorded lower tick for a given pool. Takes a `PoolId` `poolId` and returns the
stored `tickLowerLast` value.

[.contract-item]
[[LimitOrderHook-getOrderId-struct-PoolKey-int24-bool-]]
==== `[.contract-item-name]#++getOrderId++#++(struct PoolKey key, int24 tickLower, bool zeroForOne) → OrderIdLibrary.OrderId++` [.item-kind]#public#

Retrieves the order id for a given pool position. Takes a `PoolKey` `key`, target `tickLower`, and direction
`zeroForOne` indicating whether it's buying currency0 or currency1. Returns the {OrderId} associated with this
position, or the default order id if no order exists.

[.contract-item]
[[LimitOrderHook-getOrderInfo-OrderIdLibrary-OrderId-]]
==== `[.contract-item-name]#++getOrderInfo++#++(OrderIdLibrary.OrderId orderId) → bool filled, Currency currency0, Currency currency1, uint256 principalCredited0, uint256 principalCredited1, uint256 accFee0PerLiqX128, uint256 accFee1PerLiqX128, uint128 liquidityTotal++` [.item-kind]#external#

Get the order info for a given order id. Takes an {OrderId} `orderId` and returns the order info.

`accFee0PerLiqX128` and `accFee1PerLiqX128` are the fees credited to the order per unit of liquidity, as
`X128` fixed point values. Both only ever increase, and an owner's checkpoints are never above them.

[.contract-item]
[[LimitOrderHook-getUserInfo-OrderIdLibrary-OrderId-address-]]
==== `[.contract-item-name]#++getUserInfo++#++(OrderIdLibrary.OrderId orderId, address owner) → struct LimitOrderHook.UserInfo++` [.item-kind]#external#

Get the info an order holds for one of its owners. Takes an {OrderId} `orderId` and `owner` address and
returns the liquidity that owner placed and the values the order's fee accumulators are read against for it.

The difference between an accumulator and its checkpoint, over `liquidity`, is the amount of fees the owner
is owed.

[.contract-item]
[[LimitOrderHook-getHookPermissions--]]
==== `[.contract-item-name]#++getHookPermissions++#++() → struct Hooks.Permissions permissions++` [.item-kind]#public#

Get the hook permissions for this contract. Returns a `Hooks.Permissions` struct configured to enable
`afterInitialize` and `afterSwap` hooks while disabling all other hooks.

[.contract-item]
[[LimitOrderHook-Place-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-]]
==== `[.contract-item-name]#++Place++#++(address indexed owner, OrderIdLibrary.OrderId indexed orderId, struct PoolKey key, int24 tickLower, bool zeroForOne, uint128 liquidity)++` [.item-kind]#event#

Emitted when an `owner` places a limit order with the given `orderId`, in the pool identified by `key`,
at the given `tickLower`, `zeroForOne` indicating the direction of the order, and `liquidity` the amount of liquidity
added.

[.contract-item]
[[LimitOrderHook-Fill-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-]]
==== `[.contract-item-name]#++Fill++#++(OrderIdLibrary.OrderId indexed orderId, struct PoolKey key, int24 tickLower, bool zeroForOne)++` [.item-kind]#event#

Emitted when a limit order with the given `orderId` is filled in the pool identified by `key`,
at the given `tickLower`, `zeroForOne` indicating the direction of the order.

[.contract-item]
[[LimitOrderHook-Cancel-address-OrderIdLibrary-OrderId-struct-PoolKey-int24-bool-uint128-]]
==== `[.contract-item-name]#++Cancel++#++(address indexed owner, OrderIdLibrary.OrderId indexed orderId, struct PoolKey key, int24 tickLower, bool zeroForOne, uint128 liquidity)++` [.item-kind]#event#

Emitted when an `owner` cancels a limit order with the given `orderId`, in the pool identified by `key`,
at the given `tickLower`, `zeroForOne` indicating the direction of the order, and `liquidity` the amount of liquidity
removed.

[.contract-item]
[[LimitOrderHook-Withdraw-address-OrderIdLibrary-OrderId-uint128-]]
==== `[.contract-item-name]#++Withdraw++#++(address indexed owner, OrderIdLibrary.OrderId indexed orderId, uint128 liquidity)++` [.item-kind]#event#

Emitted when an `owner` withdraws their `liquidity` from a limit order with the given `orderId`, in the pool identified by `key`,
at the given `tickLower`, `zeroForOne` indicating the direction of the order.

[.contract-item]
[[LimitOrderHook-ZeroLiquidity--]]
==== `[.contract-item-name]#++ZeroLiquidity++#++()++` [.item-kind]#error#

Zero liquidity was attempted to be added or removed.

[.contract-item]
[[LimitOrderHook-InRange--]]
==== `[.contract-item-name]#++InRange++#++()++` [.item-kind]#error#

Limit order was placed in range.

[.contract-item]
[[LimitOrderHook-CrossedRange--]]
==== `[.contract-item-name]#++CrossedRange++#++()++` [.item-kind]#error#

Limit order placed on the wrong side of the range.

[.contract-item]
[[LimitOrderHook-Filled--]]
==== `[.contract-item-name]#++Filled++#++()++` [.item-kind]#error#

Limit order was already filled.

[.contract-item]
[[LimitOrderHook-NotFilled--]]
==== `[.contract-item-name]#++NotFilled++#++()++` [.item-kind]#error#

Limit order is not filled.

[.contract-item]
[[LimitOrderHook-NativeCurrencyUnsupported--]]
==== `[.contract-item-name]#++NativeCurrencyUnsupported++#++()++` [.item-kind]#error#

Limit order was placed in a pool holding the native currency.

[.contract-item]
[[LimitOrderHook-ZERO_BYTES-bytes]]
==== `bytes [.contract-item-name]#++ZERO_BYTES++#` [.item-kind]#internal constant#

The zero bytes.

[.contract-item]
[[LimitOrderHook-ORDER_ID_DEFAULT-OrderIdLibrary-OrderId]]
==== `OrderIdLibrary.OrderId [.contract-item-name]#++ORDER_ID_DEFAULT++#` [.item-kind]#internal constant#

The default order id, used to indicate that an order is not yet initialized.

:AlreadyInitialized: pass:normal[xref:#ReHypothecationHook-AlreadyInitialized--[`++AlreadyInitialized++`]]
:NotInitialized: pass:normal[xref:#ReHypothecationHook-NotInitialized--[`++NotInitialized++`]]
:ZeroShares: pass:normal[xref:#ReHypothecationHook-ZeroShares--[`++ZeroShares++`]]
:InvalidMsgValue: pass:normal[xref:#ReHypothecationHook-InvalidMsgValue--[`++InvalidMsgValue++`]]
:RefundFailed: pass:normal[xref:#ReHypothecationHook-RefundFailed--[`++RefundFailed++`]]
:LiquidityNotAllowed: pass:normal[xref:#ReHypothecationHook-LiquidityNotAllowed--[`++LiquidityNotAllowed++`]]
:NotSeeded: pass:normal[xref:#ReHypothecationHook-NotSeeded--[`++NotSeeded++`]]
:AlreadySeeded: pass:normal[xref:#ReHypothecationHook-AlreadySeeded--[`++AlreadySeeded++`]]
:InsufficientSeed: pass:normal[xref:#ReHypothecationHook-InsufficientSeed-uint256-uint256-[`++InsufficientSeed++`]]
:JITLocked: pass:normal[xref:#ReHypothecationHook-JITLocked--[`++JITLocked++`]]
:ReHypothecatedLiquidityAdded: pass:normal[xref:#ReHypothecationHook-ReHypothecatedLiquidityAdded-address-struct-PoolKey-uint256-uint256-uint256-[`++ReHypothecatedLiquidityAdded++`]]
:ReHypothecatedLiquidityRemoved: pass:normal[xref:#ReHypothecationHook-ReHypothecatedLiquidityRemoved-address-struct-PoolKey-uint256-uint256-uint256-[`++ReHypothecatedLiquidityRemoved++`]]
:getPoolKey: pass:normal[xref:#ReHypothecationHook-getPoolKey--[`++getPoolKey++`]]
:_beforeInitialize: pass:normal[xref:#ReHypothecationHook-_beforeInitialize-address-struct-PoolKey-uint160-[`++_beforeInitialize++`]]
:seedLiquidity: pass:normal[xref:#ReHypothecationHook-seedLiquidity-uint256-uint256-[`++seedLiquidity++`]]
:addReHypothecatedLiquidity: pass:normal[xref:#ReHypothecationHook-addReHypothecatedLiquidity-uint256-[`++addReHypothecatedLiquidity++`]]
:removeReHypothecatedLiquidity: pass:normal[xref:#ReHypothecationHook-removeReHypothecatedLiquidity-uint256-[`++removeReHypothecatedLiquidity++`]]
:_beforeSwap: pass:normal[xref:#ReHypothecationHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-[`++_beforeSwap++`]]
:_afterSwap: pass:normal[xref:#ReHypothecationHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-[`++_afterSwap++`]]
:_resolveHookDelta: pass:normal[xref:#ReHypothecationHook-_resolveHookDelta-Currency-[`++_resolveHookDelta++`]]
:_beforeAddLiquidity: pass:normal[xref:#ReHypothecationHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-[`++_beforeAddLiquidity++`]]
:_beforeRemoveLiquidity: pass:normal[xref:#ReHypothecationHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-[`++_beforeRemoveLiquidity++`]]
:previewMint: pass:normal[xref:#ReHypothecationHook-previewMint-uint256-[`++previewMint++`]]
:previewRedeem: pass:normal[xref:#ReHypothecationHook-previewRedeem-uint256-[`++previewRedeem++`]]
:_sharesToAmounts: pass:normal[xref:#ReHypothecationHook-_sharesToAmounts-uint256-enum-Math-Rounding-[`++_sharesToAmounts++`]]
:_shareToAmount: pass:normal[xref:#ReHypothecationHook-_shareToAmount-uint256-Currency-enum-Math-Rounding-[`++_shareToAmount++`]]
:_decimalsOffset: pass:normal[xref:#ReHypothecationHook-_decimalsOffset--[`++_decimalsOffset++`]]
:_getLiquidityToUse: pass:normal[xref:#ReHypothecationHook-_getLiquidityToUse-int24-int24-[`++_getLiquidityToUse++`]]
:_getHookPositionLiquidity: pass:normal[xref:#ReHypothecationHook-_getHookPositionLiquidity--[`++_getHookPositionLiquidity++`]]
:getTickLower: pass:normal[xref:#ReHypothecationHook-getTickLower--[`++getTickLower++`]]
:getTickUpper: pass:normal[xref:#ReHypothecationHook-getTickUpper--[`++getTickUpper++`]]
:_modifyLiquidity: pass:normal[xref:#ReHypothecationHook-_modifyLiquidity-int256-[`++_modifyLiquidity++`]]
:_transferFromSenderToHook: pass:normal[xref:#ReHypothecationHook-_transferFromSenderToHook-Currency-uint256-address-[`++_transferFromSenderToHook++`]]
:_transferFromHookToSender: pass:normal[xref:#ReHypothecationHook-_transferFromHookToSender-Currency-uint256-address-[`++_transferFromHookToSender++`]]
:getCurrencyYieldSource: pass:normal[xref:#ReHypothecationHook-getCurrencyYieldSource-Currency-[`++getCurrencyYieldSource++`]]
:_depositToYieldSource: pass:normal[xref:#ReHypothecationHook-_depositToYieldSource-Currency-uint256-[`++_depositToYieldSource++`]]
:_withdrawFromYieldSource: pass:normal[xref:#ReHypothecationHook-_withdrawFromYieldSource-Currency-uint256-[`++_withdrawFromYieldSource++`]]
:_getAmountInYieldSource: pass:normal[xref:#ReHypothecationHook-_getAmountInYieldSource-Currency-[`++_getAmountInYieldSource++`]]
:_getMaxWithdrawFromYieldSource: pass:normal[xref:#ReHypothecationHook-_getMaxWithdrawFromYieldSource-Currency-[`++_getMaxWithdrawFromYieldSource++`]]
:getHookPermissions: pass:normal[xref:#ReHypothecationHook-getHookPermissions--[`++getHookPermissions++`]]
:receive: pass:normal[xref:#ReHypothecationHook-receive--[`++receive++`]]

[.contract]
[[ReHypothecationHook]]
=== `++ReHypothecationHook++` link:https://github.com/OpenZeppelin/uniswap-hooks/blob/master/src/general/ReHypothecationHook.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import "uniswap-hooks/src/general/ReHypothecationHook.sol";
```

A Uniswap V4 hook that enables liquidity rehypothecation into external yield sources.

Allows users to deposit assets into external yield-generating sources (i.e. ERC-4626 vaults or lending protocols)
while maintaining that same liquidity available for swaps, by performing Just-in-Time (JIT) liquidity provisioning.

Assets earn yield at the yield sources when idle, before being temporarily injected as liquidity into the pool only
when needed for swap execution, then immediately withdrawn back to yield sources to continue earning yield.

Conceptually, the hook acts as an intermediary that manages:
- the user-facing ERC20 share token (representing rehypothecated liquidity).
- the underlying relationship between yield sources deposits and the pool's liquidity.

Since the hook must own the liquidity positions in both the external yield sources and the pool in order to transfer it
between the two, a single hook-owned liquidity position is shared between all the liquidity providers, defaulting to a
UniswapV2 like full-range position.

NOTE: Since the hook owns the single liquidity position, liquidity must be added and removed in the same ratio as the
balances in the yield sources.

NOTE: Since the hook owns the single liquidity position, it is possible to perform "leveraged liquidity" strategies,
which would give better pricing to swappers at the cost of the profitability of LP's and increased risks. See {_getLiquidityToUse}

NOTE: A pool must be seeded via {seedLiquidity} before liquidity can be added through {addReHypothecatedLiquidity}.
Seeding is allowed whenever the pool has no outstanding shares, i.e. at genesis or to revive the pool after a full
withdrawal. The seed sets the ratio and mints shares as `sqrt(amount0 * amount1)`, in a UniswapV2 like fashion.
From there, a share represents a proportional claim over the hook's balances in the yield sources.

WARNING: As the assets are rehypothecated into external yield sources, there is direct exposure to their risks,
such as variations in the yield rates, rebalances, impermanent loss, and other risks associated.

WARNING: This hook relies on the PoolManager singleton token reserves for flash accounting debts and credits during swaps.
During `afterSwap`, the hook briefly generates token debts to the PoolManager even before users transfer their swap tokens.
As a consequence, the PoolManager singleton may lack sufficient reserves for illiquid tokens in the instants between the swap
executed and the posterior payment from the user, preventing swaps from being executed until the PoolManager accumulates enough tokens.
Although it is very unlikely to happen, note that direct liquidity provision to the pool is disabled, so the hook is the sole
liquidity provider for its pool.

WARNING: Liquidity additions and removals may be affected by slippage. Users can protect against unexpected slippage
in general by verifying the amount received is as expected, using a wrapper that performs these checks.

WARNING: This is experimental software and is provided on an "as is" and "as available" basis.
We do not give any warranties and will not be liable for any losses incurred through any use of
this code base.
_Available since v1.2.0_

[.contract-index]
.Functions
--
* {xref-ReHypothecationHook-getPoolKey--}[`++getPoolKey()++`]
* {xref-ReHypothecationHook-_beforeInitialize-address-struct-PoolKey-uint160-}[`++_beforeInitialize(, key, )++`]
* {xref-ReHypothecationHook-seedLiquidity-uint256-uint256-}[`++seedLiquidity(amount0, amount1)++`]
* {xref-ReHypothecationHook-addReHypothecatedLiquidity-uint256-}[`++addReHypothecatedLiquidity(shares)++`]
* {xref-ReHypothecationHook-removeReHypothecatedLiquidity-uint256-}[`++removeReHypothecatedLiquidity(shares)++`]
* {xref-ReHypothecationHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++_beforeSwap(, , , )++`]
* {xref-ReHypothecationHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++_afterSwap(, key, , , )++`]
* {xref-ReHypothecationHook-_resolveHookDelta-Currency-}[`++_resolveHookDelta(currency)++`]
* {xref-ReHypothecationHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeAddLiquidity(, , , )++`]
* {xref-ReHypothecationHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++_beforeRemoveLiquidity(, , , )++`]
* {xref-ReHypothecationHook-previewMint-uint256-}[`++previewMint(shares)++`]
* {xref-ReHypothecationHook-previewRedeem-uint256-}[`++previewRedeem(shares)++`]
* {xref-ReHypothecationHook-_sharesToAmounts-uint256-enum-Math-Rounding-}[`++_sharesToAmounts(shares, rounding)++`]
* {xref-ReHypothecationHook-_shareToAmount-uint256-Currency-enum-Math-Rounding-}[`++_shareToAmount(shares, currency, rounding)++`]
* {xref-ReHypothecationHook-_decimalsOffset--}[`++_decimalsOffset()++`]
* {xref-ReHypothecationHook-_getLiquidityToUse-int24-int24-}[`++_getLiquidityToUse(tickLower, tickUpper)++`]
* {xref-ReHypothecationHook-_getHookPositionLiquidity--}[`++_getHookPositionLiquidity()++`]
* {xref-ReHypothecationHook-getTickLower--}[`++getTickLower()++`]
* {xref-ReHypothecationHook-getTickUpper--}[`++getTickUpper()++`]
* {xref-ReHypothecationHook-_modifyLiquidity-int256-}[`++_modifyLiquidity(liquidityDelta)++`]
* {xref-ReHypothecationHook-_transferFromSenderToHook-Currency-uint256-address-}[`++_transferFromSenderToHook(currency, amount, sender)++`]
* {xref-ReHypothecationHook-_transferFromHookToSender-Currency-uint256-address-}[`++_transferFromHookToSender(currency, amount, sender)++`]
* {xref-ReHypothecationHook-getCurrencyYieldSource-Currency-}[`++getCurrencyYieldSource(currency)++`]
* {xref-ReHypothecationHook-_depositToYieldSource-Currency-uint256-}[`++_depositToYieldSource(currency, amount)++`]
* {xref-ReHypothecationHook-_withdrawFromYieldSource-Currency-uint256-}[`++_withdrawFromYieldSource(currency, amount)++`]
* {xref-ReHypothecationHook-_getAmountInYieldSource-Currency-}[`++_getAmountInYieldSource(currency)++`]
* {xref-ReHypothecationHook-_getMaxWithdrawFromYieldSource-Currency-}[`++_getMaxWithdrawFromYieldSource(currency)++`]
* {xref-ReHypothecationHook-getHookPermissions--}[`++getHookPermissions()++`]
* {xref-ReHypothecationHook-receive--}[`++receive()++`]

[.contract-subindex-inherited]
.ReentrancyGuardTransient
* {xref-ReentrancyGuardTransient-_reentrancyGuardEntered--}[`++_reentrancyGuardEntered()++`]
* {xref-ReentrancyGuardTransient-_reentrancyGuardStorageSlot--}[`++_reentrancyGuardStorageSlot()++`]

[.contract-subindex-inherited]
.ERC20
* {xref-ERC20-name--}[`++name()++`]
* {xref-ERC20-symbol--}[`++symbol()++`]
* {xref-ERC20-decimals--}[`++decimals()++`]
* {xref-ERC20-totalSupply--}[`++totalSupply()++`]
* {xref-ERC20-balanceOf-address-}[`++balanceOf(account)++`]
* {xref-ERC20-transfer-address-uint256-}[`++transfer(to, value)++`]
* {xref-ERC20-allowance-address-address-}[`++allowance(owner, spender)++`]
* {xref-ERC20-approve-address-uint256-}[`++approve(spender, value)++`]
* {xref-ERC20-transferFrom-address-address-uint256-}[`++transferFrom(from, to, value)++`]
* {xref-ERC20-_transfer-address-address-uint256-}[`++_transfer(from, to, value)++`]
* {xref-ERC20-_update-address-address-uint256-}[`++_update(from, to, value)++`]
* {xref-ERC20-_mint-address-uint256-}[`++_mint(account, value)++`]
* {xref-ERC20-_burn-address-uint256-}[`++_burn(account, value)++`]
* {xref-ERC20-_approve-address-address-uint256-}[`++_approve(owner, spender, value)++`]
* {xref-ERC20-_approve-address-address-uint256-bool-}[`++_approve(owner, spender, value, emitEvent)++`]
* {xref-ERC20-_spendAllowance-address-address-uint256-}[`++_spendAllowance(owner, spender, value)++`]

[.contract-subindex-inherited]
.IERC20Errors

[.contract-subindex-inherited]
.IERC20Metadata

[.contract-subindex-inherited]
.IERC20

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-_validateHookAddress-contract-BaseHook-}[`++_validateHookAddress(hook)++`]
* {xref-BaseHook-beforeInitialize-address-struct-PoolKey-uint160-}[`++beforeInitialize(sender, key, sqrtPriceX96)++`]
* {xref-BaseHook-afterInitialize-address-struct-PoolKey-uint160-int24-}[`++afterInitialize(sender, key, sqrtPriceX96, tick)++`]
* {xref-BaseHook-_afterInitialize-address-struct-PoolKey-uint160-int24-}[`++_afterInitialize(, , , )++`]
* {xref-BaseHook-beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeAddLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-}[`++beforeRemoveLiquidity(sender, key, params, hookData)++`]
* {xref-BaseHook-afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterAddLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-_afterAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterAddLiquidity(, , , , , )++`]
* {xref-BaseHook-afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++afterRemoveLiquidity(sender, key, params, delta0, delta1, hookData)++`]
* {xref-BaseHook-_afterRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-BalanceDelta-BalanceDelta-bytes-}[`++_afterRemoveLiquidity(, , , , , )++`]
* {xref-BaseHook-beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-}[`++beforeSwap(sender, key, params, hookData)++`]
* {xref-BaseHook-afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-}[`++afterSwap(sender, key, params, delta, hookData)++`]
* {xref-BaseHook-beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++beforeDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_beforeDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_beforeDonate(, , , , )++`]
* {xref-BaseHook-afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++afterDonate(sender, key, amount0, amount1, hookData)++`]
* {xref-BaseHook-_afterDonate-address-struct-PoolKey-uint256-uint256-bytes-}[`++_afterDonate(, , , , )++`]
* {xref-BaseHook-poolManager-contract-IPoolManager}[`++poolManager()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Events
--
* {xref-ReHypothecationHook-ReHypothecatedLiquidityAdded-address-struct-PoolKey-uint256-uint256-uint256-}[`++ReHypothecatedLiquidityAdded(sender, poolKey, shares, amount0, amount1)++`]
* {xref-ReHypothecationHook-ReHypothecatedLiquidityRemoved-address-struct-PoolKey-uint256-uint256-uint256-}[`++ReHypothecatedLiquidityRemoved(sender, poolKey, shares, amount0, amount1)++`]

[.contract-subindex-inherited]
.ReentrancyGuardTransient

[.contract-subindex-inherited]
.ERC20

[.contract-subindex-inherited]
.IERC20Errors

[.contract-subindex-inherited]
.IERC20Metadata

[.contract-subindex-inherited]
.IERC20
* {xref-IERC20-Transfer-address-address-uint256-}[`++Transfer(from, to, value)++`]
* {xref-IERC20-Approval-address-address-uint256-}[`++Approval(owner, spender, value)++`]

[.contract-subindex-inherited]
.BaseHook

[.contract-subindex-inherited]
.IHooks

--

[.contract-index]
.Errors
--
* {xref-ReHypothecationHook-AlreadyInitialized--}[`++AlreadyInitialized()++`]
* {xref-ReHypothecationHook-NotInitialized--}[`++NotInitialized()++`]
* {xref-ReHypothecationHook-ZeroShares--}[`++ZeroShares()++`]
* {xref-ReHypothecationHook-InvalidMsgValue--}[`++InvalidMsgValue()++`]
* {xref-ReHypothecationHook-RefundFailed--}[`++RefundFailed()++`]
* {xref-ReHypothecationHook-LiquidityNotAllowed--}[`++LiquidityNotAllowed()++`]
* {xref-ReHypothecationHook-NotSeeded--}[`++NotSeeded()++`]
* {xref-ReHypothecationHook-AlreadySeeded--}[`++AlreadySeeded()++`]
* {xref-ReHypothecationHook-InsufficientSeed-uint256-uint256-}[`++InsufficientSeed(shares, minShares)++`]
* {xref-ReHypothecationHook-JITLocked--}[`++JITLocked()++`]

[.contract-subindex-inherited]
.ReentrancyGuardTransient
* {xref-ReentrancyGuardTransient-ReentrancyGuardReentrantCall--}[`++ReentrancyGuardReentrantCall()++`]

[.contract-subindex-inherited]
.ERC20

[.contract-subindex-inherited]
.IERC20Errors
* {xref-IERC20Errors-ERC20InsufficientBalance-address-uint256-uint256-}[`++ERC20InsufficientBalance(sender, balance, needed)++`]
* {xref-IERC20Errors-ERC20InvalidSender-address-}[`++ERC20InvalidSender(sender)++`]
* {xref-IERC20Errors-ERC20InvalidReceiver-address-}[`++ERC20InvalidReceiver(receiver)++`]
* {xref-IERC20Errors-ERC20InsufficientAllowance-address-uint256-uint256-}[`++ERC20InsufficientAllowance(spender, allowance, needed)++`]
* {xref-IERC20Errors-ERC20InvalidApprover-address-}[`++ERC20InvalidApprover(approver)++`]
* {xref-IERC20Errors-ERC20InvalidSpender-address-}[`++ERC20InvalidSpender(spender)++`]

[.contract-subindex-inherited]
.IERC20Metadata

[.contract-subindex-inherited]
.IERC20

[.contract-subindex-inherited]
.BaseHook
* {xref-BaseHook-HookNotImplemented--}[`++HookNotImplemented()++`]
* {xref-BaseHook-NotPoolManager--}[`++NotPoolManager()++`]
* {xref-BaseHook-InvalidPool--}[`++InvalidPool()++`]

[.contract-subindex-inherited]
.IHooks

--

[.contract-item]
[[ReHypothecationHook-getPoolKey--]]
==== `[.contract-item-name]#++getPoolKey++#++() → struct PoolKey poolKey++` [.item-kind]#public#

Returns the `poolKey` for the hook pool. Note that the hook supports only one pool key.

[.contract-item]
[[ReHypothecationHook-_beforeInitialize-address-struct-PoolKey-uint160-]]
==== `[.contract-item-name]#++_beforeInitialize++#++(address, struct PoolKey key, uint160) → bytes4++` [.item-kind]#internal#

Initialize the hook's `poolKey` pool. The key stored by the hook is unique and
should not be modified so that it can safely be used across the hook's lifecycle.
Note that the hook supports only one pool key.

WARNING: Pool initialization is permissionless and permanently binds the hook to the first key it sees,
so a third party can front-run it with an unintended pool. Initialize the pool atomically with the hook's
deployment, or override this function to reject an unexpected key.

[.contract-item]
[[ReHypothecationHook-seedLiquidity-uint256-uint256-]]
==== `[.contract-item-name]#++seedLiquidity++#++(uint256 amount0, uint256 amount1) → uint256 shares, BalanceDelta delta++` [.item-kind]#public#

Seeds the pool with its first liquidity, depositing `amount0` of `currency0` and `amount1` of
`currency1` into the yield sources and minting `sqrt(amount0 * amount1)` shares to the caller, in a
UniswapV2 like fashion. The deposited amounts set the ratio at which {addReHypothecatedLiquidity}
prices every later addition.

Callable permissionlessly whenever the pool has no outstanding shares: at genesis, or to revive the pool
after a full withdrawal. The minted shares must be at least `100 * 10 ** _decimalsOffset()`, so the supply
dominates the virtual-shares offset used in {_shareToAmount} and the share price cannot be inflated.

Returns the `shares` minted and a balance `delta` representing the assets deposited into the hook.

NOTE: The amounts should be provided close to the pool's current price, otherwise part of the seeded
liquidity may sit idle until swaps rebalance it. See {_getLiquidityToUse}.

WARNING: A third party can front-run the intended seed with a heavily skewed ratio. Since
{_getLiquidityToUse} is bounded by the scarcer side, the hook is then left with negligible usable liquidity
and cannot serve swaps. Deposited assets stay redeemable, and seeding reopens once the supply returns to
zero. Consider seeding atomically with pool initialization, or overriding this function to restrict the caller.

Requirements:
- Pool must be initialized
- Pool must have no outstanding shares (`totalSupply() == 0`)
- Resulting shares must be at least `100 * 10 ** _decimalsOffset()`
- Sender must have approved the hook to spend the required tokens

[.contract-item]
[[ReHypothecationHook-addReHypothecatedLiquidity-uint256-]]
==== `[.contract-item-name]#++addReHypothecatedLiquidity++#++(uint256 shares) → BalanceDelta delta++` [.item-kind]#public#

Adds rehypothecated liquidity to their corresponding yield sources and mints `shares` to the `receiver`.

Liquidity is added in the ratio determined by the hook's existing balances in yield sources.
Assets are deposited into yield sources where they earn yield when idle and can be dynamically
 used as pool liquidity during swaps.

Returns a balance `delta` representing the assets deposited into the hook.

Requirements:
- Pool must be initialized
- Pool must have been seeded (see {seedLiquidity})
- Sender must have sufficient token balances
- Sender must have approved the hook to spend the required tokens

[.contract-item]
[[ReHypothecationHook-removeReHypothecatedLiquidity-uint256-]]
==== `[.contract-item-name]#++removeReHypothecatedLiquidity++#++(uint256 shares) → BalanceDelta delta++` [.item-kind]#public#

Removes rehypothecated liquidity from their corresponding yield sources and burns `shares` from the caller.

Liquidity is withdrawn in the ratio determined by the hook's existing balances in yield sources.
Assets are withdrawn from yield sources where they were generating yield, allowing users to exit their
rehypothecated position and reclaim their underlying tokens.

Returns a balance `delta` representing the assets withdrawn from the hook.

Requirements:
- Pool must be initialized
- Sender must have sufficient shares for the desired liquidity withdrawal

[.contract-item]
[[ReHypothecationHook-_beforeSwap-address-struct-PoolKey-struct-SwapParams-bytes-]]
==== `[.contract-item-name]#++_beforeSwap++#++(address, struct PoolKey, struct SwapParams, bytes) → bytes4, BeforeSwapDelta, uint24++` [.item-kind]#internal#

Hook executed before a swap operation to provide liquidity from rehypothecated assets.

Gets the amount of liquidity to be provided from yield sources and temporarily adds it to the pool,
in a Just-in-Time provision of liquidity.

Note that at this point there are no actual transfers of tokens happening to the pool, instead,
thanks to the Flash Accounting model, this addition creates a currencyDelta to the hook, which
must be settled during the `_afterSwap` function before locking the poolManager again.

[.contract-item]
[[ReHypothecationHook-_afterSwap-address-struct-PoolKey-struct-SwapParams-BalanceDelta-bytes-]]
==== `[.contract-item-name]#++_afterSwap++#++(address, struct PoolKey key, struct SwapParams, BalanceDelta, bytes) → bytes4, int128++` [.item-kind]#internal#

Hook executed after a swap operation to remove temporary liquidity and rebalance assets.

Removes the liquidity that was temporarily added in `_beforeSwap`, and resolves the hook's
deltas in each currency in order to neutralize any pending debits or credits.

[.contract-item]
[[ReHypothecationHook-_resolveHookDelta-Currency-]]
==== `[.contract-item-name]#++_resolveHookDelta++#++(Currency currency)++` [.item-kind]#internal#

Takes or settles any pending `currencyDelta` delta with the poolManager by transferring from the yield
sources to the poolManager and vice versa, effectively neutralizing the Flash Accounting deltas before being
able to lock the poolManager again.

[.contract-item]
[[ReHypothecationHook-_beforeAddLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-]]
==== `[.contract-item-name]#++_beforeAddLiquidity++#++(address, struct PoolKey, struct ModifyLiquidityParams, bytes) → bytes4++` [.item-kind]#internal#

Blocks direct liquidity provision to the pool by third parties, so the hook remains the pool's sole
liquidity provider. This prevents external positions from interfering with the hook's just-in-time liquidity,
such as saturating the position's tick boundaries and reverting subsequent swaps.

Note that the hook's own just-in-time liquidity provisioning is unaffected, since the `PoolManager` skips hook
callbacks when the hook itself is modifying liquidity.

[.contract-item]
[[ReHypothecationHook-_beforeRemoveLiquidity-address-struct-PoolKey-struct-ModifyLiquidityParams-bytes-]]
==== `[.contract-item-name]#++_beforeRemoveLiquidity++#++(address, struct PoolKey, struct ModifyLiquidityParams, bytes) → bytes4++` [.item-kind]#internal#

Blocks direct liquidity removal from the pool by third parties. See {_beforeAddLiquidity}.

[.contract-item]
[[ReHypothecationHook-previewMint-uint256-]]
==== `[.contract-item-name]#++previewMint++#++(uint256 shares) → uint256 amount0, uint256 amount1++` [.item-kind]#public#

Preview the amounts of currency0 and currency1 required for minting a specific amount of shares.

NOTE: Rounds up, benefiting current liquidity providers.

[.contract-item]
[[ReHypothecationHook-previewRedeem-uint256-]]
==== `[.contract-item-name]#++previewRedeem++#++(uint256 shares) → uint256 amount0, uint256 amount1++` [.item-kind]#public#

Preview the amounts of currency0 and currency1 to be received for redeeming a specific amount of shares.

NOTE: Rounds down, benefiting current liquidity providers.

[.contract-item]
[[ReHypothecationHook-_sharesToAmounts-uint256-enum-Math-Rounding-]]
==== `[.contract-item-name]#++_sharesToAmounts++#++(uint256 shares, enum Math.Rounding rounding) → uint256 amount0, uint256 amount1++` [.item-kind]#internal#

Calculates the amounts of currency0 and currency1 equivalent to a given amount of `shares`, as a
proportional claim over the hook's balances in the yield sources, using the given rounding direction.

Reverts with {NotSeeded} when no shares have been minted yet, since the pool has no defined ratio before
{seedLiquidity}.

[.contract-item]
[[ReHypothecationHook-_shareToAmount-uint256-Currency-enum-Math-Rounding-]]
==== `[.contract-item-name]#++_shareToAmount++#++(uint256 shares, Currency currency, enum Math.Rounding rounding) → uint256 amount++` [.item-kind]#internal#

Converts a given `shares` amount to the corresponding `currency` amount, as its proportional claim
over the hook's balance of `currency` in the yield source, using the given rounding direction.

Uses an EIP-4626 like virtual offset (see {_decimalsOffset}) to defend the share price against inflation,
so a share is worth `(balance + 1) / (totalSupply + 10 ** _decimalsOffset())` of the `currency` balance.
Reverts with {NotSeeded} before the pool is seeded.

[.contract-item]
[[ReHypothecationHook-_decimalsOffset--]]
==== `[.contract-item-name]#++_decimalsOffset++#++() → uint8++` [.item-kind]#internal#

Returns the decimal offset used for the EIP-4626 like virtual shares that defend the share price
against inflation. The initial supply minted by {seedLiquidity} is required to be at least
`100 * 10 ** _decimalsOffset()`, keeping the maximum share price drift around 1%.

Defaults to `6`, which suits most token pairs. Can be overridden to strengthen the defense with a higher
offset, at the cost of a larger minimum seed, for example for high-decimal pairs.

[.contract-item]
[[ReHypothecationHook-_getLiquidityToUse-int24-int24-]]
==== `[.contract-item-name]#++_getLiquidityToUse++#++(int24 tickLower, int24 tickUpper) → uint256++` [.item-kind]#internal#

Calculates the `liquidity` to be provided just-in-time for incoming swaps.

By default, returns the maximum liquidity that can be provided given the balances the hook can
currently withdraw from the yield sources (see {_getMaxWithdrawFromYieldSource}), so the position
removed in `afterSwap` never exceeds what the yield sources can return in the same transaction.

Since the internal pool price (ratio of currency0 to currency1) must be preserved for providing
liquidity to the single hook-owned position range, not necessarily all the assets in the yield
sources may be utilizable as liquidity if the ratio has diverged from the internal pool price.

i.e if the pool price is currently [1:1], but due to divergences in the yield sources the assets
are [100, 110], then only [100, 100] is utilizable and will be returned by this function in equivalent
liquidity units, as it is the maximum amount of assets utilizable given the current pool price ratio.

NOTE: Since liquidity is provided and withdrawn transiently during flash accounting, it can be virtually
inflated for performing "leveraged liquidity" strategies, which would give better pricing to swappers at
the cost of the profitability of LP's and increased risks.

[.contract-item]
[[ReHypothecationHook-_getHookPositionLiquidity--]]
==== `[.contract-item-name]#++_getHookPositionLiquidity++#++() → uint128 liquidity++` [.item-kind]#internal#

Retrieves the current `liquidity` of the hook owned liquidity position in the `_poolKey` pool.

NOTE: Given that just-in-time liquidity provisioning is performed, this function will only return non-zero values
while the liquidity is briefly inside the pool, which is exclusively between `beforeSwap` and `afterSwap`). It will
return zero in any other point in the hook lifecycle. For determining the hook balances in any other point, use
{_getAmountInYieldSource}.

[.contract-item]
[[ReHypothecationHook-getTickLower--]]
==== `[.contract-item-name]#++getTickLower++#++() → int24++` [.item-kind]#public#

Returns the lower tick boundary for the hook's liquidity position.

Can be overridden to customize the tick boundary.

[.contract-item]
[[ReHypothecationHook-getTickUpper--]]
==== `[.contract-item-name]#++getTickUpper++#++() → int24++` [.item-kind]#public#

Returns the upper tick boundary for the hook's liquidity position.

Can be overridden to customize the tick boundary.

[.contract-item]
[[ReHypothecationHook-_modifyLiquidity-int256-]]
==== `[.contract-item-name]#++_modifyLiquidity++#++(int256 liquidityDelta) → BalanceDelta delta++` [.item-kind]#internal#

Modifies the hook's liquidity position in the pool, at the tick bounds snapshotted for the current
swap (see {_snapshotActiveTicks}).

Positive liquidityDelta adds liquidity, while negative removes it.

[.contract-item]
[[ReHypothecationHook-_transferFromSenderToHook-Currency-uint256-address-]]
==== `[.contract-item-name]#++_transferFromSenderToHook++#++(Currency currency, uint256 amount, address sender)++` [.item-kind]#internal#

[.contract-item]
[[ReHypothecationHook-_transferFromHookToSender-Currency-uint256-address-]]
==== `[.contract-item-name]#++_transferFromHookToSender++#++(Currency currency, uint256 amount, address sender)++` [.item-kind]#internal#

Transfers the `amount` of `currency` from the hook to the `sender`.

[.contract-item]
[[ReHypothecationHook-getCurrencyYieldSource-Currency-]]
==== `[.contract-item-name]#++getCurrencyYieldSource++#++(Currency currency) → address yieldSource++` [.item-kind]#public#

Returns the `yieldSource` address for a given `currency`.

Note: Must be implemented and adapted for the desired type of yield sources, such as
 ERC-4626 Vaults, or any custom DeFi protocol interface, optionally handling native currency.

[.contract-item]
[[ReHypothecationHook-_depositToYieldSource-Currency-uint256-]]
==== `[.contract-item-name]#++_depositToYieldSource++#++(Currency currency, uint256 amount)++` [.item-kind]#internal#

Deposits a specified `amount` of `currency` into its corresponding yield source.

Note: Must be implemented and adapted for the desired type of yield sources, such as
 ERC-4626 Vaults, or any custom DeFi protocol interface, optionally handling native currency.

[.contract-item]
[[ReHypothecationHook-_withdrawFromYieldSource-Currency-uint256-]]
==== `[.contract-item-name]#++_withdrawFromYieldSource++#++(Currency currency, uint256 amount)++` [.item-kind]#internal#

Withdraws a specified `amount` of `currency` from its corresponding yield source.

Note: Must be implemented and adapted for the desired type of yield sources, such as
 ERC-4626 Vaults, or any custom DeFi protocol interface, optionally handling native currency.

[.contract-item]
[[ReHypothecationHook-_getAmountInYieldSource-Currency-]]
==== `[.contract-item-name]#++_getAmountInYieldSource++#++(Currency currency) → uint256 amount++` [.item-kind]#internal#

Gets the `amount` of `currency` deposited in its corresponding yield source.

Note: Must be implemented and adapted for the desired type of yield sources, such as
 ERC-4626 Vaults, or any custom DeFi protocol interface, optionally handling native currency.

[.contract-item]
[[ReHypothecationHook-_getMaxWithdrawFromYieldSource-Currency-]]
==== `[.contract-item-name]#++_getMaxWithdrawFromYieldSource++#++(Currency currency) → uint256++` [.item-kind]#internal#

Returns the maximum `amount` of `currency` that can currently be withdrawn from its yield source.

Used to size the just-in-time liquidity provided during swaps, so the hook never provisions more than it
can withdraw back in the same transaction. Share pricing instead uses {_getAmountInYieldSource}, the full
reported balance.

Defaults to {_getAmountInYieldSource}. Override for yield sources whose immediately-withdrawable amount can
be below the reported balance, such as ERC-4626 `maxWithdraw`, or capped, gated or fee-charging sources.

[.contract-item]
[[ReHypothecationHook-getHookPermissions--]]
==== `[.contract-item-name]#++getHookPermissions++#++() → struct Hooks.Permissions permissions++` [.item-kind]#public#

[.contract-item]
[[ReHypothecationHook-receive--]]
==== `[.contract-item-name]#++receive++#++()++` [.item-kind]#external#

Allows the hook to receive native ETH from the yield sources.

[.contract-item]
[[ReHypothecationHook-ReHypothecatedLiquidityAdded-address-struct-PoolKey-uint256-uint256-uint256-]]
==== `[.contract-item-name]#++ReHypothecatedLiquidityAdded++#++(address indexed sender, struct PoolKey indexed poolKey, uint256 shares, uint256 amount0, uint256 amount1)++` [.item-kind]#event#

Emitted when a `sender` adds rehypothecated `shares` to the `poolKey` pool,
 transferring `amount0` of `currency0` and `amount1` of `currency1` to the hook.

[.contract-item]
[[ReHypothecationHook-ReHypothecatedLiquidityRemoved-address-struct-PoolKey-uint256-uint256-uint256-]]
==== `[.contract-item-name]#++ReHypothecatedLiquidityRemoved++#++(address indexed sender, struct PoolKey indexed poolKey, uint256 shares, uint256 amount0, uint256 amount1)++` [.item-kind]#event#

Emitted when a `sender` removes rehypothecated `liquidity` from the `poolKey` pool,
 receiving `amount0` of `currency0` and `amount1` of `currency1` from the hook.

[.contract-item]
[[ReHypothecationHook-AlreadyInitialized--]]
==== `[.contract-item-name]#++AlreadyInitialized++#++()++` [.item-kind]#error#

Error thrown when trying to initialize a pool that has already been initialized.

[.contract-item]
[[ReHypothecationHook-NotInitialized--]]
==== `[.contract-item-name]#++NotInitialized++#++()++` [.item-kind]#error#

Error thrown when attempting to interact with a pool that has not been initialized.

[.contract-item]
[[ReHypothecationHook-ZeroShares--]]
==== `[.contract-item-name]#++ZeroShares++#++()++` [.item-kind]#error#

Error thrown when attempting to add or remove liquidity with zero shares.

[.contract-item]
[[ReHypothecationHook-InvalidMsgValue--]]
==== `[.contract-item-name]#++InvalidMsgValue++#++()++` [.item-kind]#error#

Error thrown when the message value doesn't match the expected amount for native ETH deposits.

[.contract-item]
[[ReHypothecationHook-RefundFailed--]]
==== `[.contract-item-name]#++RefundFailed++#++()++` [.item-kind]#error#

Error thrown when the refund fails.

[.contract-item]
[[ReHypothecationHook-LiquidityNotAllowed--]]
==== `[.contract-item-name]#++LiquidityNotAllowed++#++()++` [.item-kind]#error#

Error thrown when a third party attempts to provide or remove liquidity directly on the pool.

[.contract-item]
[[ReHypothecationHook-NotSeeded--]]
==== `[.contract-item-name]#++NotSeeded++#++()++` [.item-kind]#error#

Error thrown when adding liquidity before the pool has been seeded.

[.contract-item]
[[ReHypothecationHook-AlreadySeeded--]]
==== `[.contract-item-name]#++AlreadySeeded++#++()++` [.item-kind]#error#

Error thrown when seeding a pool that still has outstanding shares.

[.contract-item]
[[ReHypothecationHook-InsufficientSeed-uint256-uint256-]]
==== `[.contract-item-name]#++InsufficientSeed++#++(uint256 shares, uint256 minShares)++` [.item-kind]#error#

Error thrown when a seed would mint fewer than the minimum safe initial `shares`, given `minShares`.

[.contract-item]
[[ReHypothecationHook-JITLocked--]]
==== `[.contract-item-name]#++JITLocked++#++()++` [.item-kind]#error#

Error thrown when a liquidity operation and the just-in-time settlement would overlap,
to prevent reentrancy across the JIT lock.

