:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]
:CurrencySettler: pass:normal[xref:utils.adoc#CurrencySettler[`CurrencySettler`]]
:xref-CurrencySettler-settle-Currency-contract-IPoolManager-address-uint256-bool-: xref:utils.adoc#CurrencySettler-settle-Currency-contract-IPoolManager-address-uint256-bool-
:xref-CurrencySettler-take-Currency-contract-IPoolManager-address-uint256-bool-: xref:utils.adoc#CurrencySettler-take-Currency-contract-IPoolManager-address-uint256-bool-
:xref-CurrencySettler-InvalidNativePayer-address-: xref:utils.adoc#CurrencySettler-InvalidNativePayer-address-
= Utilities

[.readme-notice]
NOTE: This document is better viewed on the docs page.

Libraries and general purpose utilities to help develop hooks.

 * {CurrencySettler}: Library used to interact with the `PoolManager` to settle any open deltas, with support for ERC-6909 and native currencies.
 * {LiquidityMath}:  Library with helper functions for liquidity math.

== Libraries

:InvalidNativePayer: pass:normal[xref:#CurrencySettler-InvalidNativePayer-address-[`++InvalidNativePayer++`]]
:settle: pass:normal[xref:#CurrencySettler-settle-Currency-contract-IPoolManager-address-uint256-bool-[`++settle++`]]
:take: pass:normal[xref:#CurrencySettler-take-Currency-contract-IPoolManager-address-uint256-bool-[`++take++`]]

[.contract]
[[CurrencySettler]]
=== `++CurrencySettler++` link:https://github.com/OpenZeppelin/uniswap-hooks/blob/master/src/utils/CurrencySettler.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import "uniswap-hooks/src/utils/CurrencySettler.sol";
```

Library used to interact with the `PoolManager` to settle any open deltas.
To settle a positive delta (a credit to the user), a user may take or mint.
To settle a negative delta (a debt on the user), a user may transfer or burn to pay off a debt.

Based on the https://github.com/Uniswap/v4-core/blob/main/test/utils/CurrencySettler.sol[Uniswap v4 test utils implementation].

NOTE: Deltas are synced before any ERC-20 transfers in {settle} function.

IMPORTANT: Moving an underlying token hands execution to code the hook does not control: {take} calls the
recipient for the native currency, and both {take} and {settle} call the token contract for an ERC-20. The
`PoolManager` is unlocked there, so that code can reach the hook partway through an operation, when the state
it exposes is not yet consistent. Follow checks-effects-interactions and update that state before either call.
The ERC-6909 paths and a native {settle} reach only the `PoolManager`.

[.contract-index]
.Functions
--
* {xref-CurrencySettler-settle-Currency-contract-IPoolManager-address-uint256-bool-}[`++settle(currency, poolManager, payer, amount, burn)++`]
* {xref-CurrencySettler-take-Currency-contract-IPoolManager-address-uint256-bool-}[`++take(currency, poolManager, recipient, amount, claims)++`]

--

[.contract-index]
.Errors
--
* {xref-CurrencySettler-InvalidNativePayer-address-}[`++InvalidNativePayer(payer)++`]

--

[.contract-item]
[[CurrencySettler-settle-Currency-contract-IPoolManager-address-uint256-bool-]]
==== `[.contract-item-name]#++settle++#++(Currency currency, contract IPoolManager poolManager, address payer, uint256 amount, bool burn)++` [.item-kind]#internal#

[.contract-item]
[[CurrencySettler-take-Currency-contract-IPoolManager-address-uint256-bool-]]
==== `[.contract-item-name]#++take++#++(Currency currency, contract IPoolManager poolManager, address recipient, uint256 amount, bool claims)++` [.item-kind]#internal#

[.contract-item]
[[CurrencySettler-InvalidNativePayer-address-]]
==== `[.contract-item-name]#++InvalidNativePayer++#++(address payer)++` [.item-kind]#error#

The native currency was settled on behalf of a `payer` other than the contract paying it.

