name: checks
on:
  push:
    branches:
      - master
      - next-v*
      - release-v*
  pull_request: {}
env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: npm run lint

  tests:
    name: Foundry tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Install Foundry dependencies
        run: forge install
        shell: bash

      - name: Build and check contract sizes
        run: forge build --sizes --skip test

      - name: Run tests
        run: forge test -v
        env:
          FOUNDRY_PROFILE: deep

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      
      - name: Generate coverage
        run: forge coverage --report lcov
      
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - uses: crytic/slither-action@v0.4.1
        with:
          node-version: 20.x
          slither-version: 0.11.3

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@v2.1
        with:
          check_hidden: true
          check_filenames: true
          skip: package-lock.json,*.pdf,vendor